### ISSUE TITLE
CRD changes after upgrading controller -gen version

### ISSUE THREAD

**Issue by linglingye001** [kubernetes-sigs/controller-tools#1014]
Hi team, we have upgraded the `controller-gen` tool version from `v0.8.0` to `0.15.0` , and there's no change in API markers. After executing `make manifests`, `CustomResourceDefinitionStatus` section was gone. I'm not sure if this change is expected and will this have any impact? Thanks
![image](https://github.com/user-attachments/assets/f2deef6a-020b-4de8-bc61-b17b33a995a3)

**Comment by sbueringer** [comment]
This is expected and it won't have any impact

**Comment by linglingye001** [comment]
I see, thanks!
