### ISSUE TITLE
Support for selectable fields for custom resources

### ISSUE THREAD

**Issue by everesio** [kubernetes-sigs/controller-tools#1039]
Kubernetes 1.31 introduces the ability to define field selectors for custom resources.
You can find more details in the official documentation [crd-selectable-fields](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#crd-selectable-fields)

This issue is a feature request to add support for this functionality to controller-tools, including the addition markers and extending the documentation to explain how the feature should be used.

**Comment by everesio** [comment]
Since adding a new CRD marker is very simple, I could create a PR. I would propose the following changes.

1. New marker in the crd.go
```golang
	must(markers.MakeDefinition("kubebuilder:selectablefield", markers.DescribesType, SelectableField{})).
		WithHelp(SelectableField{}.Help()),
```  

2. SelectableField in the crd.go
```golang
// +controllertools:marker:generateHelp:category=CRD

// SelectableField adds a field that may be used with field selectors.
type SelectableField struct {
	// JSONPath specifies the jsonpath expression which is used to produce a field selector value.
	JSONPath string `marker:"JSONPath"`
}

func (s SelectableField) ApplyToCRD(crd *apiext.CustomResourceDefinitionSpec, version string) error {
	var selectableFields *[]apiext.SelectableField
	for i := range crd.Versions {
		ver := &crd.Versions[i]
		if ver.Name != version {
			continue
		}
		selectableFields = &ver.SelectableFields
		break
	}
	if selectableFields == nil {
		return fmt.Errorf("selectable field applied to version %q not in CRD", version)
	}

	*selectableFields = append(*selectableFields, apiext.SelectableField{
		JSONPath: s.JSONPath,
	})

	return nil
}
```

3. Code generated by helpgen in the zz_generated.markerhelp.go would be
```golang
func (SelectableField) Help() *markers.DefinitionHelp {
	return &markers.DefinitionHelp{
		Category: "CRD",
		DetailedHelp: markers.DetailedHelp{
			Summary: "adds a field that may be used with field selectors.",
			Details: "",
		},
		FieldHelp: map[string]markers.DetailedHelp{
			"JSONPath": {
				Summary: "specifies the jsonpath expression which is used to produce a field selector value.",
				Details: "",
			},
		},
	}
}
```

**Comment by sbueringer** [comment]
I look into the details on the PR, but feel free to open a PR for it

**Comment by everesio** [comment]
PR was merged https://github.com/kubernetes-sigs/controller-tools/pull/1050

**Comment by everesio** [comment]
@sbueringer Thank you !

**Comment by sbueringer** [comment]
Thank you as well! :)

**Comment by pmalek** [comment]
Thanks for implementing this 🙇 This will greatly improve operations on some of the CRDs that we use (and kubebuilder's lack of support for this code marker has been the only missing point for us).

One thing that I believe should still be added is a mention about this in https://book.kubebuilder.io/reference/markers/crd, right? Is this just a matter of pulling in the latest controller tools to kubebuilder or we need to update https://github.com/kubernetes-sigs/kubebuilder/tree/master/docs/book/src/reference/markers ?

**Comment by sbueringer** [comment]
@pmalek Just created the v0.16.4 release.

Not sure what is needed on the kubebuilder side (cc @camilamacedo86)
