### ISSUE TITLE
controller-tools and controller-runtime use similar but incompatible versioning tables

### ISSUE THREAD

**Issue by adammw** [kubernetes-sigs/controller-tools#1041]
Ripe for confusion. Also unclear which version I should be downloading to match with controller-runtime...

![image](https://github.com/user-attachments/assets/c0ed1a2d-f0c6-4e3a-a7f9-0f2608ec7b88)
![image](https://github.com/user-attachments/assets/73c0e2c0-e2b3-4466-b4bd-70828077669e)

**Comment by sbueringer** [comment]
One of the tables should have ct in the first column instead of cr

**Comment by sbueringer** [comment]
There should be no need to match CR and CT versions

**Comment by sbueringer** [comment]
/close

see comments above
