### ISSUE TITLE
controller-gen cannot be properly versioned without patching the existing code

### ISSUE THREAD

**Issue by josvazg** [kubernetes-sigs/controller-tools#1046]
The [version computing code assumes the usage](https://github.com/kubernetes-sigs/controller-tools/blob/main/pkg/version/version.go#L39) of the `controller-gen` will always be as a module:
```
$ go get github.com/controller-tools/cmd/controller-gen@v0.16.1
```

Moreover, downloading the [official released binaries from this repo directly](https://github.com/kubernetes-sigs/controller-tools/releases)  they still render `(devel)`as the binary version.

This is not CI or reproducible environment friendly. Ideally, you would define your dependency version on some file, then just have it available in your environment.

Using the module approach and updating your `go.mod` does not make the binary available after `go mod tidy`, so the CI will not be able to use `controller-gen`.

There is no ready available packaging such as with brew or Debian.

Reproducible builds with versioning exist from nix, [by patching the versioning code in this repository](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/tools/kubernetes-controller-tools/version.patch).

Given than using the CLI generator tool as a module is not natively supported by Go, and that a binary distribution of some kind is required, we would like to propose the following change.
- Use the industry standard way to set a version with `ldflags`, for instance `-X sigs.k8s.io/controller-tools/pkg/version.Version=X.Y.Z`
- When Version is not an empty string, override the usual return `info.Main.Version` with such local `Version` value.
- Change the builds to set the version at compile time, so official releases will render their correct version.

We are ready to follow up with a patch for this.

**Comment by s-urbaniak** [comment]
cc @vincepri

**Comment by s-urbaniak** [comment]
and cc @sbueringer 🙏

**Comment by josvazg** [comment]
Thanks @sbueringer !

Just posted #1049

**Comment by josvazg** [comment]
Fix merged, we can close this now
