### ISSUE TITLE
Merge CRD objects into each other

### ISSUE THREAD

**Issue by TrayserCassa** [kubernetes-sigs/controller-tools#1107]
Hi,

I’m currently working on reusing a struct that defines a container configuration for both jobs and deployments. Since these configurations can have different values (e.g., the image field), I structured it like this:

```
Container                                        ContainerSpec `json:"container"`
AdminDeploymentContainer      ContainerSpec `json:"adminDeploymentContainer"`
MigrationJobContainer                ContainerSpec `json:"migrationJobContainer"`
```
The goal is as follows:

If Container specifies `image:abc` and AdminDeploymentContainer specifies `image: xyz`, the admin deployment should run with `xyz`, while everything else uses `abc`.

I was considering adding a Merge function to handle these cases, in addition to the existing DeepCopyInto function.
Does this approach make sense, or is there an existing PR or issue I might have overlooked?

**Comment by sbueringer** [comment]
I'm not aware of anything in CT that would help here

**Comment by camilamacedo86** [comment]
IHMO it should be closed as won't to do

**Comment by sbueringer** [comment]
Agree. I think there is nothing we can do in CT
/close
