### ISSUE TITLE
Add command-line option to run controller-gen in verify mode

### ISSUE THREAD

**Issue by ebblake** [kubernetes-sigs/controller-tools#1108]
In my project, we were debating about how to have CI ensure that a developer has remembered to run 'make generate' (a wrapper around controller-gen invocation) every time they touch an API file.  For example, if you change a foo_types.go source file to fix a typo, but don't rerun controller-gen, the typo will still persist in the generated crd/foo.yaml file, but everything still builds (the API itself didn't change); without some sort of CI verification, this would result in an out-of-sync file in a release.

But I couldn't find any existing command-line option to controller-gen that puts it in a verify mode.  It would be nice to have an output:verify that checks that the files that controller-gen WOULD have produced are byte-for-byte identical to the files already present in the output location (error if an expected output file is missing or has stale contents).  Then CI can merely check that the user checked in any changed generated files as part of their commit.

In the short term, we ended up writing a hairy rule that moved original files out of the way, reran the generator with its normal output, then ran diff on the original vs generated files.

**Comment by camilamacedo86** [comment]
Hi @ebblake,  

If you re-run `controller-gen`, it will always return the same result if no changes exist. 
IMO: The problem that you are trying to solve should be done in your project CI
You must ensure that before any PR gets merged, you do a sanity test and verify that everything is fine.

### Example scenario

In **Kubebuilder**, we have a similar check to ensure consistency. For every PR, we verify if the samples under testdata were properly -regenerated updated. If they do not, the PR fails. This approach helps us maintain the integrity of our generated content.

### Proposed Solution  

You can implement a similar check in your project by:  
1. Creating a CI process that runs `make generate manifests`.  
2. Validating whether there are any Git diffs after the command.  
3. Failing the CI process if diffs are detected.  

For reference, here is how we handle this in Kubebuilder:  
[Check Script in Kubebuilder](https://github.com/kubernetes-sigs/kubebuilder/blob/master/test/testdata/check.sh)


### Example

```
## Script: Validate `make generate manifests`

Below is a script to check if `make generate manifests` produces consistent results. This script ensures that running the command does not introduce any unexpected changes in the repository.

```bash
#!/bin/bash

if [[ $(git status ${check_directory} --porcelain) ]]; then
  exit 1
fi

make generate manifests

if [[ $(git status ${check_directory} --porcelain) ]]; then
  echo "Not synced failed!"
  echo "Run 'make generate manifests'."
  git status ${check_directory} --porcelain
  git diff ${check_directory}
  exit 1
fi
```

Then you can call it in GitHub action

**Comment by ebblake** [comment]
A git hook directly running controller-gen is a nice idea - but it presupposes that controller-gen is available in the platform running the git server and CI.  In my case, it wasn't (not all the world is github, after all) - the git server only had enough installed to spawn up containers for CI, and it was the container running controller-gen, but the container didn't have access to git.  But I'll explore whether I can enhance my CI environment to either get golang and controller-gen installed without needing a container, or at least tweaking my CI container to (ab)use git as a means of checking that a run of controller-gen didn't produce any changes rather than my current ad hoc copy and diff (I have more control over the container run during CI than I do of the git server).  Still, a verify option would make it easier to do this with controller-gen itself, instead of having to rely on an external tool like git or diff to do a post-processing pass.

**Comment by camilamacedo86** [comment]
Hi @ebblake,

You can perform the same check regardless of whether your project is published. Even if you’re not using GitHub, you can create a CI check to achieve the same result following the proposed idea. Just call the command and verify if it has or has not changed.

However, you are suggesting here a subcommand to check if the manifests are generated. **IHMO it does not bring value since you can simply call the generate commands and verify if has changes or not for your use case, it does not seems to fit in the tool itself.** In my opinion, there’s no real need to add this subcommand.

I hope that helps out.

**Comment by sbueringer** [comment]
One addition. If tools like `git` or `diff` are used they can also output a nice diff to show what exactly has changed.

Example: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_cluster-api/11616/pull-cluster-api-verify-main/1871167802627330048

**Comment by camilamacedo86** [comment]
IHMO this could be closed as reffered
