### ISSUE TITLE
For basic validation and defaulting webhooks, default to a stronger failurepolicy

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/controller-tools#127]
Since we're working on making the cases of webhook use for defaulting and validation easier, we might want to consider generating webhook configs with a "stronger" failurepolicy (i.e. not "ignore") for those, so that bad objects can't sneak into the cluster if our webhook server fails.

cc @mengqiy

**Comment by estroz** [comment]
@DirectXMan12 I assume this feature still needs working on. Has there been any work done on determining which failurepolicy is the best option yet?

**Comment by mengqiy** [comment]
This is already done. kubebuilder currently defaults it to `fail`.
e.g. https://github.com/kubernetes-sigs/kubebuilder/blob/fc60d25463298ee14da3ccb0f6c9cb9cc70af94d/testdata/project-v2/api/v1/captain_webhook.go#L37
