### ISSUE TITLE
Update controller-runtime to v0.1.10

### ISSUE THREAD

**Issue by ichekrygin** [kubernetes-sigs/controller-tools#132]
To keep up-to-date with `controller-runtime` and `controller-tools` in general.
To leverage new features:
- CRD description 
- logger

**Comment by vincepri** [comment]
The controller-runtime dependency has already been upgraded to v0.1.10

https://github.com/kubernetes-sigs/controller-tools/blob/master/Gopkg.lock#L902-L943

**Comment by ichekrygin** [comment]
my bad, wrong project  :(
