### ISSUE TITLE
struct tags containing digits are omitted from generated CRD

### ISSUE THREAD

**Issue by ckrough** [kubernetes-sigs/controller-tools#139]
Using kubebuilder 1.0.7 and 1.0.8, given a struct that includes numbers in the value of a struct field tag, the resulting generated CRD will be missing any fields that had digits in their json tag:

*struct*
```
type MySpec struct {
	Foo  string `json:"foo"`
	Bar1 string `json:"bar1"`
}
```

*command*
`go run vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go all `

*CRD snippet*
```
spec:
  properties:
    foo:
      type: string
```

**Comment by sohankunkerkar** [comment]
@ckrough It looks like your use case is not compliant with the kubernetes API guidelines. I attempted to fix a similar problem a while ago but had to close my PR. Here's the link for my PR:
https://github.com/kubernetes-sigs/controller-tools/pull/109
I hope that helps!

**Comment by ckrough** [comment]
Thanks @sohankunkerkar. I see that the [api-conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#naming-conventions) don't allow underscores or dashes, but didn't see any restriction against digits in the tag contents. 

Did I miss it?

**Comment by sohankunkerkar** [comment]
@ckrough yeah, you're right. Nothing's mentioned in the doc specifically. Probably we can ask @droot / @DirectXMan12 for their suggestions.

**Comment by DirectXMan12** [comment]
Our API conventions seem to allow it, but I can't find anywhere we've actually done it.  At the very least, we should probably complain instead of silently continuing.  I don't think I'd mind supporting it, but I also wouldn't encourage its usage.

**Comment by ckrough** [comment]
My use case ended up changing so this isn't a blocker for me anymore. Because you don't encourage it's usage, but it would be better if there was a warning/error, I'm gonna leave this Issue open anyway.
