### ISSUE TITLE
Failure: controller-gen/main.go crd processes all directories (including vendor)

### ISSUE THREAD

**Issue by ichekrygin** [kubernetes-sigs/controller-tools#148]
It appears to be a regression as a result of #144 where `apis-path` and `apis-pkg` were added only in `cmd/crd/cmd/generate.go`, whereas it should be added in both `cmd/crd/cmd/generate.go` and `cmd/controller-gen/main.go`.

This results in failure when running via `controller-gen/main.go` since it attempts to process all directories under root path (including vendor) and ultimately fails on:
`panic: Cannot get version for unversioned type sigs.k8s.io/controller-tools/pkg/internal/codegen/parse.IsAPIResource`

**Comment by mengqiy** [comment]
The offending PR was reverted in #169
