### ISSUE TITLE
CLI option to generate complete schema

### ISSUE THREAD

**Issue by redborian** [kubernetes-sigs/controller-tools#165]
Currently, in the generated CRD schema, the fields `ObjectMeta` and `TypeMeta` are just `object`s. This seems to be [by design](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/customresources-validation.md#metadata). Anyhow, there needs to be a command-line option to generate a complete schema. This will be useful for IDE consumption.

**Comment by DirectXMan12** [comment]
As an update: this is actually a relatively simple change, and should come as part of some broader refactoring work that we're working on right now.  We do want this as an option, though (I'm not sure it should be on by default -- need to talk that out).

**Comment by mengqiy** [comment]
Fixed already.
