### ISSUE TITLE
Allow generation of validation for types from k8s.io/api

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/controller-tools#167]
We currently explicitly skip types from `k8s.io/api`, for no apparent reason.  We should allow generating validation for such types, even if it's only structural (optional vs required, basic type information)

/kind feature
/priority important-soon

**Comment by sttts** [comment]
/cc @liggitt 

This would force us into at least `IntOrString`.

**Comment by liggitt** [comment]
it also will cause problems with the recursively-defined managedFields subtree

**Comment by sttts** [comment]
@liggitt can you elaborate? Would we need a "stop generation here" tag?

In general, I would very much like to see a KEP about a unified OpenAPI tag language we can use in k8s.io/api types as well, and with that make embedded much easier. This is something we might want to target in the 1.16 time frame.

**Comment by liggitt** [comment]
> @liggitt can you elaborate?

without `$ref` support, recursively defined structures can't render a complete schema for use inside a CRD

**Comment by sttts** [comment]
> without `$ref` support, recursively defined structures can't render a complete schema for use inside a CRD

It's about schema generation here. Why shouldn't crd-gen be able to parse k8s.io/api types. It will flatten the output of course, without `$ref`.

**Comment by liggitt** [comment]
How do you flatten a schema for a recursively defined type without use of $ref?

**Comment by sttts** [comment]
@liggitt you drop it. But now I see what you mean. But we should find a way to cut that off from the schema, and allow 99% of the rest.

`+no-schema`

**Comment by DirectXMan12** [comment]
For the moment, you can take a look at the behavior in the new version of controller-tools -- it explicitly overrides a few types, like `IntOrString`, since they don't have markers (tags) on them already.

**Comment by DirectXMan12** [comment]
closing, fixed by the overrides section in v0.2.0-xyz
