### ISSUE TITLE
Add flags of other generators in `controller-gen all`

### ISSUE THREAD

**Issue by janetkuo** [kubernetes-sigs/controller-tools#168]
`controller-gen all` runs all available generators, but doesn't provide flags of those generators. For example, `controller-gen crd --skip-map-validation`. It should be extended to include all those flags.

**Comment by mengqiy** [comment]
@janetkuo In what cases you will want to skip map validation?

**Comment by janetkuo** [comment]
Hmm this is no longer relevant because the code has been restructured.
