### ISSUE TITLE
"crd generate" with CRD versioning?

### ISSUE THREAD

**Issue by jonjohnsonjr** [kubernetes-sigs/controller-tools#173]
Any plans for how `crd generate` can support the upcoming [CRD versioning](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/)? Or does it work already?

E.g. there is a [`Versions`](https://github.com/kubernetes/kubernetes/blob/e318642946daab9e0330757a3556a1913bb3fc5c/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types.go#L56-L67) field that contains per-version schema, printer columns, etc.

Just curious if you have plans to support this before we adopt the tool, thanks!

**Comment by mengqiy** [comment]
We are in the process of rewriting CRD generator to get rid of `k8s.io/gengo` in our generator.
Multi-version CRD will be supported after the rewriting.

**Comment by mengqiy** [comment]
Feel free to checkout the code in https://github.com/kubernetes-sigs/controller-tools/tree/crdgenerator, it is still under development.
