### ISSUE TITLE
Setting scope: Namespaced on generated CRD

### ISSUE THREAD

**Issue by kragniz** [kubernetes-sigs/controller-tools#214]
Currently, generated CRD resources without any special annotations on resources have `spec.scope: ""` set. When applied to a cluster, this defaults to `spec.scope: Namespaced`. I would expect this to be the default output from controller-gen.

The command I'm running is:

`controller-gen crd:trivialVersions=true paths=./pkg/apis/... output:crd:dir="${output}"`

**Comment by ironcladlou** [comment]
See https://github.com/kubernetes-sigs/controller-tools/pull/220
