### ISSUE TITLE
flattening wipes out field validation on type aliases

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/controller-tools#217]
Flattening causes type alias information to override field information, which currently wipes any field specific validation.  We'll want to fix this, but we'll need to somehow merge the two sets of validation.

In case of disjoint sets of validation types this is easy.  In case of overlap (e.g. two pattern fields, two enums, etc), it's a bit more unclear what to do.  The "most correct" would probably be to use `allOf`, but that's non-structural.

@sttts

**Comment by sttts** [comment]
`allOf` is still allowed as before with structural schema. But some directives must not conflict and hence you must be able to move them outside of the allOf: 
* type, 
* title, 
* default
* additionalProperties
* nullable
* description

**Comment by sttts** [comment]
if one of those conflict on one of the allOf branches, you can
* type: error
* title: override
* default: override the more specific one? or even restrict that to field markers
* additionalProperties: push the allOf inside of the schema, i.e. `allOf:[{additionalProperties:X},{ additionalProperties:Y}] => additionalProperties:{allOf:[X,Y]}`
* nullable: disjunction, i.e. `allOf:[{nullable:true, ...},{nullable:false, ...}] => nullable:true, allOf:[..., ...]`
* description: concatenate

**Comment by DirectXMan12** [comment]
description we override currently (we just keep the field description, since that's probably what you want), otherwise looks good.

**Comment by sttts** [comment]
sounds also good @ description and title.

**Comment by sttts** [comment]
one more case to consider:

additionalProperties and properties are mutual exclusive. So if one is one allOf branch, and the other is on another branch => error
