### ISSUE TITLE
RBAC rule do not render if there is no empty row below the annotation

### ISSUE THREAD

**Issue by vincent-pli** [kubernetes-sigs/controller-tools#221]
Firstly I use
```
// +kubebuilder:rbac:groups=tektonexperimental.vincent-pli.com,resources=listenertemplates,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=tektonexperimental.vincent-pli.com,resources=listenertemplates/status,verbs=get;update;patch
func (r *ListenerTemplateReconciler) Reconcile(req ctrl.Request) (ctrl.Result, error) {
```

with out an empty row below the annotation, I find there is no RBAC stuff render, later I add a new empty row, then everything goes well.

Is that a bug?

**Comment by DirectXMan12** [comment]
No, it's intentional.  If there's no empty row, it's considered to be a marker on the function, since it's part of the function's godoc.  The rbac marker is package-level, so putting it on the function won't work.  We could probably clarify this better in the docs.

**Comment by vincent-pli** [comment]
@DirectXMan12 
Thanks a lot for clarification, that's make sense.
