### ISSUE TITLE
Versions list in the generated CRD should be sorted by version name

### ISSUE THREAD

**Issue by droot** [kubernetes-sigs/controller-tools#236]
Looks like versions list generated CRD is not stable. So if the ordering doesn't match the one persisted in the etcd, server will throw an error.

You may see an error similar to the following:

```
The CustomResourceDefinition <YOUR CRD> is invalid: spec.version: Invalid value: "v1": must match the first version in spec.versions
```

**Comment by mengqiy** [comment]
Both `spec.version` and `spec.versions` are optional.
IMO if we have more than one versions, we should just alway clear `spec.version` field.

**Comment by mengqiy** [comment]
Ref: https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/#version-priority

**Comment by DirectXMan12** [comment]
The actual issue here, I believe, is not the sorting, but the defaulting of `spec.version` using the sorted version.

Having a stable sort is nice, but what we actually need to do here is that we're consistently setting `version`.

**Comment by haiyanmeng** [comment]
> The actual issue here, I believe, is not the sorting, but the defaulting of `spec.version` using the sorted version.
> 
> Having a stable sort is nice, but what we actually need to do here is that we're consistently setting `version`.

Thanks for pointing out, Solly.

In summary, what we really need are two things:
1) make the order of CRD versions stable;
2) explicitly set `crd.Spec.Version` to the first item of the sorted CRD version list.
