### ISSUE TITLE
Support validation of array items

### ISSUE THREAD

**Issue by ekuefler** [kubernetes-sigs/controller-tools#237]
controller-gen supports validation annotations like `Pattern` on strings and `MaxItems` on arrays. I would also like to be able to apply `Pattern` to arrays so that I can validate that every string in that array matches the pattern. Same goes for all of the other single-item annotations like `Minimum` and `Maximum`.

**Comment by robbie-demuth** [comment]
I didn't find this initially, but it looks like the same issue that I just opened https://github.com/kubernetes-sigs/controller-tools/issues/342
