### ISSUE TITLE
Support struct embedding

### ISSUE THREAD

**Issue by skonto** [kubernetes-sigs/controller-tools#244]
I am hitting this one:
https://github.com/kubernetes-sigs/controller-tools/blob/abcf7d8d54b0cca0f42c470b705fd3cfe768ede3/pkg/crd/schema.go#L325 (btw there is a typo there s/enountered/encountered)
While my types are valid. They just use struct embedding.

**Comment by DirectXMan12** [comment]
can you please provide the actual struct that you're using?  Embedded fields should be handled fine.

**Comment by DirectXMan12** [comment]
you'll need to mark the field with `json:",inline"`, though

**Comment by skonto** [comment]
@DirectXMan12 thanks for the hint. I will try that.

**Comment by DirectXMan12** [comment]
yeah, that just needs the tag

**Comment by skonto** [comment]
@DirectXMan12 feel free to close it. It worked thanks!
