### ISSUE TITLE
Add an option to provide default value of spec in CRD 

### ISSUE THREAD

**Issue by gautamkmr** [kubernetes-sigs/controller-tools#250]
Currently if we want to set some default value in spec for a specified CRD its not possible (AFAIK). It would be great if we can add that support and have it available in documentation.

**Comment by DirectXMan12** [comment]
This went in in 1.15, so we should have markers to support it.

**Comment by pmorie** [comment]
@marun is this addressed by https://github.com/kubernetes-sigs/controller-tools/commit/6a7730120cada464a5dd6426b78873e74367b82d ?

**Comment by marun** [comment]
/close 

Fixed by #323
