### ISSUE TITLE
Role ordering is not stable

### ISSUE THREAD

**Issue by jgustie** [kubernetes-sigs/controller-tools#251]
Using 0.2.0-beta.3 the RBAC generator is modifying files on every pass. I think this is due to the #235 changes: the ultimate ordering of the policy rules slice is now determined by a map iteration.

I'm still transitioning from Java to Go, but I think the fix is to aggregate the `rules` keys into another slice, sort the ruleKey slice and iterate over that when building the list of policy rules.

**Comment by DirectXMan12** [comment]
they should be being sorted @haiyanmeng FYI
