### ISSUE TITLE
Update command line help and add docs for move from `deepcopy` naming to `object` naming.

### ISSUE THREAD

**Issue by alexkreidler** [kubernetes-sigs/controller-tools#261]
Across the entire web, everyone refers to the need to genreate `DeepCopy()` functions to implement the `runtime.Object` interface, and even the current help from `controller-gen -h` gives the following example: 
```
# Generate deepcopy implementations for a particular file
controller-gen deepcopy paths=./apis/v1beta1/some_types.go
```
However, the correct command is `controller-gen object paths=./apis/v1beta1/some_types.go`

Additionally, the old `k8s:deepcopy-gen` markers have been depracated in favor of `kubebuilder:object:generate`. It would be great to add this to the `kubebuilder` documentation or add some sort of more robust documentation for `controller-tools`.

PR #248 should help with updating the command-line help text, so I would love to see any updates to the documentation merged ASAP because it is really hard to get started using these tools if the most accurate information about features can be found by digging through Github issues and pull request.

However, this project is amazing, so thanks for an awesome tool!

**Comment by djzager** [comment]
@alexkreidler looking at the [kubebuilder book](https://book.kubebuilder.io/reference/markers/object.html?highlight=deepcopy#objectdeepcopy) and a more recent version of `controller-gen -h` (see below). I don't think this is an issue anymore. Can you confirm?

```
generators

+webhook                                                                                                  package  generates (partial) {Mutating,Validating}WebhookConfiguration objects.
+schemapatch:manifests=<string>[,maxDescLen=<int>]                                                        package  patches existing CRDs with new schemata.
+rbac:roleName=<string>                                                                                   package  generates ClusterRole objects.
+object[:headerFile=<string>][,year=<string>]                                                             package  generates code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
+crd[:crdVersions=<[]string>][,maxDescLen=<int>][,preserveUnknownFields=<bool>][,trivialVersions=<bool>]  package  generates CustomResourceDefinition objects.
```
