### ISSUE TITLE
Wrong deepcopy generation when using type aliased arrays or maps

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/controller-tools#262]
I'm hitting an issue when generating `deepcopy` files with `controller-gen`. If I have something like:
```golang
// IngressRules is a slice of AWS ingress rules for security groups.
type IngressRules []*IngressRule
```
It generates:
```golang
func (in IngressRules) DeepCopyInto(out *IngressRules) {
    in := &in
    *out = make(IngressRules, len(*in))
    for i := range *in {
        if (*in)[i] != nil {
            in, out := &(*in)[i], &(*out)[i]
            *out = new(IngressRule)
            (*in).DeepCopyInto(*out)
        }
    }
}
```
Which fails compilation with `cannot use &in (type *IngressRules) as type IngressRules in assignment`.

The same issue goes for `type Tags map[string]string`, where we alias Tags to a map.

Tried both latest `master` and `beta.3`

**Comment by mengqiy** [comment]
cc: @DirectXMan12

**Comment by DirectXMan12** [comment]
fascinating.  I don't think we ever have a case of `[]*Type` in our APIs in Kubernetes -- just `[]Type`, which is one of the reasons we never saw this (we're *this* close to being source-identical to k/k's deepcopy-gen on `k8s.io/api`, which is one of the informal tests for `controller-gen object).

As for the maps, we never actually use those as type aliases in Kubernetes either, so we didn't catch it (we use `map[string]string` for things though, so it's definitely something we should support).

**Comment by DirectXMan12** [comment]
at any rate, fix (and regression test) coming shortly

**Comment by DirectXMan12** [comment]
That was a doozy.  I've got a regression test in place matching your description, but can you also confirm that #275 fixes your issue?

**Comment by vincepri** [comment]
I'll test it out today

**Comment by vincepri** [comment]
@DirectXMan12 Confirmed the patch works fine!
