### ISSUE TITLE
Pattern troubles around {} chars

### ISSUE THREAD

**Issue by silasb** [kubernetes-sigs/controller-tools#272]
Using v0.2.0-beta.3  (v0.2.0-beta.4 doesn't appear to be honoring any validations)

Have a simple pattern that I'm using to validate against build IDs in my project.

```
	// +kubebuilder:validation:Pattern=^[a-z0-9]{4}$
	BuildID *string `json:"build_id,omitempty"`
```

The problem is when I use `controller-gen` I get `extra arguments provided: "}$"` error multiple times.

**Comment by cadedaniel** [comment]
I too experienced this. I set up an [example repository](https://github.com/cadedaniel/kubebuilder-pattern-validation-bug/blob/master/api/v1beta1/frigate_types.go#L30-L31 ) (minimal, used Kubebuilder to set up) which reproduces the issue.

To reproduce the issue, run `make manifests`:
```bash
$ make manifests
go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.0-beta.2
go: finding sigs.k8s.io/controller-tools/cmd/controller-gen v0.2.0-beta.2
go: finding sigs.k8s.io/controller-tools/cmd v0.2.0-beta.2
/Users/cdnamz/go/bin/controller-gen "crd:trivialVersions=true" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/Users/cdnamz/dev/kubebuilder-pattern-validation-bug/api/v1beta1/frigate_types.go:30:2: extra arguments provided: "}:role/?[a-zA-Z_0-9+=,.@\\-_/]+"
/Users/cdnamz/dev/kubebuilder-pattern-validation-bug/api/v1beta1/frigate_types.go:30:2: extra arguments provided: "}:role/?[a-zA-Z_0-9+=,.@\\-_/]+"
/Users/cdnamz/dev/kubebuilder-pattern-validation-bug/api/v1beta1/frigate_types.go:30:2: extra arguments provided: "}:role/?[a-zA-Z_0-9+=,.@\\-_/]+"
/Users/cdnamz/dev/kubebuilder-pattern-validation-bug/api/v1beta1/frigate_types.go:30:2: extra arguments provided: "}:role/?[a-zA-Z_0-9+=,.@\\-_/]+"
Error: not all generators ran succesfully
```

The error message comes from [this branch](https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/markers/parse.go#L674-L676) in `pkg/markers/parse.go`. I am guessing the parser needs to be hardened, or swapped out with a library.

**Comment by BenWUKFast** [comment]
This is a regression from V1. I'm refactoring a controller and ran into this issue.

Here's an example off UUIDv4 validation which fails due to this regression

**Comment by ggaurav10** [comment]
I had the same issue. Adding quotes worked for me:
```
	// +kubebuilder:validation:Pattern="^[a-z0-9]{4}$"
```
