### ISSUE TITLE
Marker for x-kubernetes-embedded-resource

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/controller-tools#278]
Should be straightforward -- we just need to add a validation marker for `x-kubernetes-embedded-resource`, and a test case for it to the crd integration test.

The meaning is described [in the structural schema KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190425-structural-openapi.md).

probably something like `+kubebuilder:validation:EmbeddedResource`.

/good-first-issue
/kind feature

**Comment by DirectXMan12** [comment]
May need to wait till we get 1.15 types in here to support the new field.

**Comment by hasheddan** [comment]
Would be happy to take this one!

**Comment by DirectXMan12** [comment]
sure.  We'll have 1.15 soonish

**Comment by hasheddan** [comment]
Fixed by #345

/close
