### ISSUE TITLE
controller-gen drops all validation metadata in v0.2.0-beta.4

### ISSUE THREAD

**Issue by ekuefler** [kubernetes-sigs/controller-tools#280]
After updating from v0.2.0-beta.2 to v0.2.0-beta.4, controller-gen appears to ignore all of the validation annotations I've defined in my custom types. Running `make manifests` after the update with no other changes causes all lines like `pattern` or `minItems` to be deleted from the CRDs.

**Comment by munnerz** [comment]
I can confirm this is the case with .4. .3 does *not* have the same issue, so I've rolled back for the time being 😄

**Comment by DirectXMan12** [comment]
can you post post a reproducer?  I can't seem to reproduce this on our test data.

**Comment by DirectXMan12** [comment]
88586d41f78829b7bb6b99e0fce5fadf2726879b

**Comment by DirectXMan12** [comment]
(it's fixed on master)

**Comment by mengqiy** [comment]
Closing in favor of v0.2.0-beta.5 release.

**Comment by ekuefler** [comment]
Confirming fixed in 0.2.0-beta.5
