### ISSUE TITLE
How do I add labels for the generated CRD yaml?

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/controller-tools#285]
We like to add label to our generated CRD yamls. This gives users a quick way to check the installation process worked or not. 

The main issue I see is that there is parser for `MapType`. Is this something that can be supported?

**Comment by hasbro17** [comment]
@mengqiy @DirectXMan12 Is it possible to do this in the `v0.2.0+` releases of `controller-gen`?

Plus what would be the marker path for setting object metadata if that's possible? It's not immediately clear from the [marker pkg godocs](https://godoc.org/sigs.k8s.io/controller-tools/pkg/markers).

**Comment by tamalsaha** [comment]
We use `kubectl` to apply labels to generated crd yamls. https://github.com/stashed/stash/blob/5fb54194c1ff5faf7d7d15176a4107c127319395/Makefile#L227

This workaround is working for us.

**Comment by mengqiy** [comment]
Adding a label is not specific to CRD, it can be considered as a customization of an object.
One way to add the label is using kustomize. Use either the commonLabel or a patch to add the label.

@DirectXMan12  WDYT?

**Comment by hasbro17** [comment]
@mengqiy Fair point. It's not specific to the CRD's API so this probably doesn't need to come from `_types.go`.
A kustomize patch would be better, or an additional step after running the crd generator like @tamalsaha's work around.

**Comment by DirectXMan12** [comment]
yeah, either a kustomize patch, kubectl, etc is the right approach.  Closing.
