### ISSUE TITLE
Support generating CRD yamls without the description fields

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/controller-tools#288]
The generated yamls has the description field which is useful but I have a case where it makes the CRD to cross the 1 MB limit. I would like to have the option to avoid generating the description field in the CRD yaml.

**Comment by droot** [comment]
Few possible options here worth considering:
- skip description generation for all fields
- truncate description field
- Keep the descriptions at the top level fields and drop for fields level below

**Comment by droot** [comment]
We discussed this offline and supporting an option to specify truncation limit for description field seems to be a reasonable approach.

**Comment by DirectXMan12** [comment]
fixed a while ago with the `maxDescLen` option

**Comment by tamalsaha** [comment]
@DirectXMan12 , is it possible to set this on per CRD basis in a single api group?  Right now, I pass this to the controller-tools binary. So, description of  all the crds in an api group is truncated.

**Comment by DirectXMan12** [comment]
it's not currently possible (mainly since we consider this a hack and would like to move to a place where this isn't a problem).  You could just run controller-gen separately for that API group.

**Comment by tamalsaha** [comment]
> You could just run controller-gen separately for that API group.

That does not work for me. All my CRDs are in the same api group but one CRD is causing problem. Is it possible to run YAML generation for a single CRD in an api group?
