### ISSUE TITLE
controller-gen doesn't work with k8s.io/apiextensions-apiserver

### ISSUE THREAD

**Issue by jiachengxu** [kubernetes-sigs/controller-tools#291]
Hi folks,

I use controller-gen integrated with Kubebuilder to generate RBAC, webhook and CRDs for my project, there is a command called `make manifests` to run:
 `controller-gen "crd:trivialVersions=true" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases`   
to generate everything, but it doesn't work for me since I have `k8s.io/apiextensions-apiserver` in my `go.mod` as a dependency, the following error messages are poping out:
`/Users/maxwell/go/pkg/mod/k8s.io/apiextensions-apiserver@v0.0.0-20190409022649-727a075fdec8/pkg/apis/apiextensions/v1beta1/types_jsonschema.go:63:2: enountered struct field "Raw" without JSON tag in type "JSON"
/Users/maxwell/go/pkg/mod/k8s.io/apiextensions-apiserver@v0.0.0-20190409022649-727a075fdec8/pkg/apis/apiextensions/v1beta1/types_jsonschema.go:29:24: unsupported type "float64"
/Users/maxwell/go/pkg/mod/k8s.io/apiextensions-apiserver@v0.0.0-20190409022649-727a075fdec8/pkg/apis/apiextensions/v1beta1/types_jsonschema.go:31:24: unsupported type "float64"
/Users/maxwell/go/pkg/mod/k8s.io/apiextensions-apiserver@v0.0.0-20190409022649-727a075fdec8/pkg/apis/apiextensions/v1beta1/types_jsonschema.go:39:24: unsupported type "float64"
/Users/maxwell/go/pkg/mod/k8s.io/apiextensions-apiserver@v0.0.0-20190409022649-727a075fdec8/pkg/apis/apiextensions/v1beta1/types_jsonschema.go:85:2: enountered struct field "Schema" without JSON tag in type "JSONSchemaPropsOrArray"
/Users/maxwell/go/pkg/mod/k8s.io/apiextensions-apiserver@v0.0.0-20190409022649-727a075fdec8/pkg/apis/apiextensions/v1beta1/types_jsonschema.go:86:2: enountered struct field "JSONSchemas" without JSON tag in type "JSONSchemaPropsOrArray"
/Users/maxwell/go/pkg/mod/k8s.io/apiextensions-apiserver@v0.0.0-20190409022649-727a075fdec8/pkg/apis/apiextensions/v1beta1/types_jsonschema.go:105:2: enountered struct field "Allows" without JSON tag in type "JSONSchemaPropsOrBool"
/Users/maxwell/go/pkg/mod/k8s.io/apiextensions-apiserver@v0.0.0-20190409022649-727a075fdec8/pkg/apis/apiextensions/v1beta1/types_jsonschema.go:106:2: enountered struct field "Schema" without JSON tag in type "JSONSchemaPropsOrBool"
/Users/maxwell/go/pkg/mod/k8s.io/apiextensions-apiserver@v0.0.0-20190409022649-727a075fdec8/pkg/apis/apiextensions/v1beta1/types_jsonschema.go:127:2: enountered struct field "Schema" without JSON tag in type "JSONSchemaPropsOrStringArray"
/Users/maxwell/go/pkg/mod/k8s.io/apiextensions-apiserver@v0.0.0-20190409022649-727a075fdec8/pkg/apis/apiextensions/v1beta1/types_jsonschema.go:128:2: enountered struct field "Property" without JSON tag in type "JSONSchemaPropsOrStringArray"
Error: not all generators ran successfully
`
Any ideas about why this happened?

Thanks,
Jiacheng

**Comment by munnerz** [comment]
Can you share your types.go file containing your API definitions? It looks like you are depending on something in the apiextensions-apiserver API group 🤔 fwiw, #277 is a fix for:

```
/Users/maxwell/go/pkg/mod/k8s.io/apiextensions-apiserver@v0.0.0-20190409022649-727a075fdec8/pkg/apis/apiextensions/v1beta1/types_jsonschema.go:63:2: enountered struct field "Raw" without JSON tag in type "JSON"
```

**Comment by jiachengxu** [comment]
@munnerz , yes, you are right, my API definitions depend on the apiextensions-apiserver API group, and thanks for the info :)!

**Comment by munnerz** [comment]
It looks like similar PRs for the `JSONSchemaPropsOrArray`, `JSONSchemaPropsOrBool` and `JSONSchemaPropsOrStringArray` need to be made in order to make controller-tools work for you too!

**Comment by jiachengxu** [comment]
Hi @munnerz, yes, you are right, would you mind me working on this? I think your PR is a good example for me to start and I can send the similar PRs for `JSONSchemaPropsOrArray`, `JSONSchemaPropsOrBool` and `JSONSchemaPropsOrStringArray`.

**Comment by DirectXMan12** [comment]
I'm curious as to why your types depend on apiextensions?  Are you embedding a CRD spec in your types?

**Comment by maxsmythe** [comment]
[Gatekeeper](github.com/open-policy-agent/gatekeeper) is embedding a CRD spec into its `ConstraintTemplate` resource:

https://github.com/open-policy-agent/frameworks/blob/1307ba72bce38ee3cf44f94def1bbc41eb4ffa90/constraint/pkg/apis/templates/v1beta1/constrainttemplate_types.go#L46

**Comment by thetechnick** [comment]
@jiachengxu and I are also embedding the CRD Spec into one of our resources.
We are working on tooling that manages CRDs dynamically.

**Comment by DirectXMan12** [comment]
We might want to better generically detect when something implements the JSON interfaces manually -- we have the typechecking info, so it should be possilbe.

/help

**Comment by muvaf** [comment]
I have a type that embeds `CustomResourceDefinitionSpec` type which suffers from [this issue](https://github.com/crossplane/crossplane/blob/55793a570a8a2c72f0acaf5987354922997076ef/apis/apiextensions/v1alpha1/infrastructuredefinition_types.go#L33).

> We might want to better generically detect when something implements the JSON interfaces manually -- we have the typechecking info, so it should be possilbe.

@DirectXMan12 If you can give me some pointers, I can work on a PR to make it happen.

**Comment by DirectXMan12** [comment]
I *think* someone posted something recently: https://github.com/kubernetes-sigs/controller-tools/pull/427

just waiting on a test

**Comment by maxsmythe** [comment]
Great news! I look forward to ditching the old, old version of controller-gen

**Comment by maxsmythe** [comment]
/remove-lifecycle stale

How is this looking? I notice #427 is merged, but this isn't resolved. Is this just an oversight?

**Comment by DirectXMan12** [comment]
I think this is *mostly* resolved.  Technically, we should have type info for the other types, but we at least have a workaround, so I think we can *probably* close this for now.

**Comment by julianKatz** [comment]
We're still seeing this same error when using `controller-gen@v0.4.0`:

```
❯ controller-gen crd:trivialVersions=true paths=./pkg/...
/usr/local/google/home/juliankatz/go/pkg/mod/k8s.io/apiextensions-apiserver@v0.18.2/pkg/apis/apiextensions/v1beta1/types_jsonschema.go:60:24: unsupported type "float64"
/usr/local/google/home/juliankatz/go/pkg/mod/k8s.io/apiextensions-apiserver@v0.18.2/pkg/apis/apiextensions/v1beta1/types_jsonschema.go:62:24: unsupported type "float64"
/usr/local/google/home/juliankatz/go/pkg/mod/k8s.io/apiextensions-apiserver@v0.18.2/pkg/apis/apiextensions/v1beta1/types_jsonschema.go:70:24: unsupported type "float64"
github.com/open-policy-agent/frameworks/constraint/pkg/apis/templates/v1alpha1:-: CRD for ConstraintTemplate.templates.gatekeeper.sh has no storage version
Error: not all generators ran successfully
run `controller-gen crd:trivialVersions=true paths=./pkg/... -w` to see all available markers, or `controller-gen crd:trivialVersions=true paths=./pkg/... -h` for usage
```

Just to be sure:

```
❯ controller-gen --version
Version: v0.4.0
```

Any other context we/I can provide to help get this addressed?  We're stuck on `v0.1.8` in https://github.com/open-policy-agent/frameworks/tree/master/constraint

**Comment by tshak** [comment]
👋 I'm able to repro this issue on the latest build. It does not appear to be resolved. 🙏

**Comment by julianKatz** [comment]
@tshak did you use the following CRD option?

```
controller-gen crd:allowDangerousTypes=true
```

That got it going for me.  I only figured that out by looking at the PR.  Further documentation would make this a lot friendlier.

**Comment by tshak** [comment]
Thanks Julian. Sadly that does not work for me:

```
/Users/tshak/code/go/pkg/mod/k8s.io/apiextensions-apiserver@v0.18.12/pkg/apis/apiextensions/v1/types_jsonschema.go:191:2: encountered struct field "Schema" without JSON tag in type "JSONSchemaPropsOrArray"
/Users/tshak/code/go/pkg/mod/k8s.io/apiextensions-apiserver@v0.18.12/pkg/apis/apiextensions/v1/types_jsonschema.go:192:2: encountered struct field "JSONSchemas" without JSON tag in type "JSONSchemaPropsOrArray"
/Users/tshak/code/go/pkg/mod/k8s.io/apiextensions-apiserver@v0.18.12/pkg/apis/apiextensions/v1/types_jsonschema.go:211:2: encountered struct field "Allows" without JSON tag in type "JSONSchemaPropsOrBool"
/Users/tshak/code/go/pkg/mod/k8s.io/apiextensions-apiserver@v0.18.12/pkg/apis/apiextensions/v1/types_jsonschema.go:212:2: encountered struct field "Schema" without JSON tag in type "JSONSchemaPropsOrBool"
/Users/tshak/code/go/pkg/mod/k8s.io/apiextensions-apiserver@v0.18.12/pkg/apis/apiextensions/v1/types_jsonschema.go:233:2: encountered struct field "Schema" without JSON tag in type "JSONSchemaPropsOrStringArray"
/Users/tshak/code/go/pkg/mod/k8s.io/apiextensions-apiserver@v0.18.12/pkg/apis/apiextensions/v1/types_jsonschema.go:234:2: encountered struct field "Property" without JSON tag in type "JSONSchemaPropsOrStringArray"
```

I'm running `controller-gen` as part of go code generation:

```
//go:generate go run -tags generate sigs.k8s.io/controller-tools/cmd/controller-gen object:headerFile=../../hack/boilerplate.go.txt paths=./... crd:trivialVersions=true,crdVersions=v1,allowDangerousTypes=true output:artifacts:config=../../config/base
```

**Comment by maxsmythe** [comment]
Is the following code being vendored in?

https://github.com/kubernetes/apiextensions-apiserver/blob/a7ee1efe41fc19623ce57f047c7595d624df4c17/pkg/apis/apiextensions/v1/marshal.go#L28-L37

If gomod is pruning that code for some reason, then the `implementsJSONMarshaler` interface wouldn't be satisfied, which means the fix in #427 wouldn't be triggered.

**Comment by tshak** [comment]
I'm using Go Modules but nevertheless I confirmed that the code exists when I `Go to Definition` in VS code. I'm on `v0.18.12` of `k8s.io/apiextensions-apiserver`. I'm not sure if any of this is relevant though as the fix in #427 was reverted in #505.

**Comment by maxsmythe** [comment]
It looks like that reversion is in v0.4.1, but not v0.4.0.

I can confirm that generating CRDs that embed JSONSchema is broken due to the reversion in #505 

@DirectXMan12 Should the reversion be un-reverted? Are there any plans to accommodate embedding JSONSchema in other ways?

**Comment by maxsmythe** [comment]
/reopen

Re-opening as this issue has been de-mitigated

**Comment by maxsmythe** [comment]
Looks like I don't have permissions to re-open. Can it be re-opened?
