### ISSUE TITLE
controller-gen Unknown supported Kind Interface when generating crd

### ISSUE THREAD

**Issue by szediktam** [kubernetes-sigs/controller-tools#294]
I use kubebuilder to building api by using crds.
when I generate crd by controller-gen, with a command:
     ```controller-gen crd```
 it occurs an error:
    ```Unknown supported Kind Interface```

The reason is, in my crd types, I use a interface to accept any object.
I want to generate a "object" item in crd. An example as following:
type RequestBody interface {
}
CRD define:
```
    body:
        description: Request body
        type: object
```

But the controller-gen donot support interface kind to generate crd.
A bug? Or any other way to make it. 
Thanks.

**Comment by DirectXMan12** [comment]
For the moment, at least, I'd use `json.RawMessage` here as the underlying type.  That should work fine.  We decided to not support this because it's not recommended as part of the Kubernetes API conventions, but we can revisit that decision if it proves onerous.

**Comment by DirectXMan12** [comment]
alternatively, `runtime.RawExtension` will covert the equivalent for specifically Kubernetes-related raw JSON blobs.

**Comment by szediktam** [comment]
Thanks for your reply. @DirectXMan12 
But how to use json.RawMessage or runtime.RawExtension to make it.
Can you show me an example?

**Comment by szediktam** [comment]
I use runtime.RawExtension as the type, and generated a object type in crd.
RawExtension.Raw is []byte, unmarshal it to interface to process the data.

**Comment by szediktam** [comment]
Using interface type is a direct idea for user to generate crd.
Maybe it is onerous to support interface type. @DirectXMan12

**Comment by DirectXMan12** [comment]
sorry, I'm having trouble parsing your issue with `RawExtension` -- it's designed for when you need to represent an arbitrary Kubernetes object.

> Using interface type is a direct idea for user to generate crd.

Sorry, I'm having trouble parsing what you're trying to say here.

**Comment by szediktam** [comment]
sorry for my poor english.
I use runtime.RawExtension to solve my problem.

But, I think it is necessary to support initerface type when generate crds by controller-gen.

**Comment by ish-xyz** [comment]
Can we please allow interfaces in the CRD generation? I don't understand why there's so much push back.
