### ISSUE TITLE
generating CRD failed because of following fields

### ISSUE THREAD

**Issue by magicsong** [kubernetes-sigs/controller-tools#297]
1. `*float64` unsupported type "float64"(seems it is forbidden by k8s )
2. including object like https://github.com/kubernetes/apimachinery/blob/6fa4771c83b36b02580b91137a4f7daf13201b24/pkg/util/intstr/intstr.go#L41:6 (but not this package). it tells me to generate json tag to such object but it is  unneccessary because the struct itself has implement the json marshal interface

**Comment by mengqiy** [comment]
Re. 1, float is not roundtrip-able, so it's not allowed in k8s.
Re. 2, see https://github.com/kubernetes-sigs/controller-tools/issues/304
