### ISSUE TITLE
Document marker locations

### ISSUE THREAD

**Issue by ghost** [kubernetes-sigs/controller-tools#313]
I'm using kubebuilder 2.0, in v1, the controller-gen version used allowed markers to be placed in function godoc position, however in controller-gen 0.2.0 it must be placed outside of that. It's worth documenting in kubebuilder, but I think it would be a good idea to get it documented in the tooling first. I can't see it mentioned anywhere or at least explicitly made clear.

Wrong example:

```go
// +kubebuilder:rbac:groups=batch,resources=jobs/status,verbs=watch;watch
// +kubebuilder:rbac:groups=art,resources=jobs,verbs=get,namespace=park
func myfunc() {

}
```

Working example:

```go
// +kubebuilder:rbac:groups=batch,resources=jobs/status,verbs=watch;watch
// +kubebuilder:rbac:groups=art,resources=jobs,verbs=get,namespace=park

func myfunc() {

}
```

**Comment by nzmsv** [comment]
Is this a regression?  It is certainly surprising that controller-gen started silently ignoring markers in previously working code.

**Comment by nzmsv** [comment]
Actually, it appears that this behavior is somewhat documented, but it is certainly confusing.  For example, see https://book.kubebuilder.io/reference/markers/rbac.html: it says the marker belongs "on package".  But if it appears anywhere else it is silently ignored.  Printing a warning would be a huge improvement.

**Comment by BenWUKFast** [comment]
I feel this is a regression pre-1.0 but I don't have the time to test I'm afraid.

Warnings would be a blessing and save a lot of head scratching (and potential malicious edits)
