### ISSUE TITLE
Unable to create schema validation with a regex that is quoted with single quotes

### ISSUE THREAD

**Issue by aanm** [kubernetes-sigs/controller-tools#315]
```
// CronJobSpec defines the desired state of CronJob
type CronJobSpec struct {
	// +kubebuilder:validation:MinLength=0

	// The schedule in Cron format, see https://en.wikipedia.org/wiki/Cron.
	Schedule string `json:"schedule"`

	// +kubebuilder:validation:Pattern='Fo{,2}'
	Foo string `json:"ip"`
}
```
```
$ make manifests
controller-gen "crd:trivialVersions=true" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
./api/v1/cronjob_types.go:35:2: extra arguments provided: ",2}'"
./api/v1/cronjob_types.go:35:2: extra arguments provided: ",2}'"
./api/v1/cronjob_types.go:35:2: extra arguments provided: ",2}'"
./api/v1/cronjob_types.go:35:2: extra arguments provided: ",2}'"
```
/kind bug

cc @DirectXMan12

**Comment by DirectXMan12** [comment]
`// +kubebuilder:validation:pattern="Fo{,2}` should work.  Anything that's not a "trivial" string must be quoted.  The quoted strings follow the rules of Go's own strings.  See https://book.kubebuilder.io/reference/markers.html#marker-syntax for more details.

Feel free to re-open if this doesn't solve your issue.

**Comment by aanm** [comment]
I did try single quotes `'` but not `"`. Thanks @DirectXMan12

**Comment by DirectXMan12** [comment]
hmm... single quotes didn't work?

**Comment by DirectXMan12** [comment]
That seems like a bug

**Comment by aanm** [comment]
@DirectXMan12 yep, I can confirm. Single quotes doesn't work.

**Comment by DirectXMan12** [comment]
huh

**Comment by DirectXMan12** [comment]
will attempt to reproduce

**Comment by DirectXMan12** [comment]
possibly a parser bug

**Comment by DirectXMan12** [comment]
Ah, too many languages floating around -- we follow Go syntax, so single quotes denote characters, not strings :-)

**Comment by DirectXMan12** [comment]
(you can use either double quotes or backticks, both of which follow Go's parsing semantics)

**Comment by aanm** [comment]
Thanks for taking a look at it!

**Comment by ryanbrainard** [comment]
For me, it choked when it got to a special char sequence like `\d+` but I was able to finally get it to work by using backticks. Single and double quotes did not work.
