### ISSUE TITLE
Does CRD controller-gen version attribution work for other binaries?

### ISSUE THREAD

**Issue by joelanford** [kubernetes-sigs/controller-tools#348]
In https://github.com/kubernetes-sigs/controller-tools/pull/338, the version of `controller-gen` that is used to generate the CRD is inserted into the CRD as an annotation.

As I understand it, this works by querying the go module metadata of the Go binary. This works well for `controller-gen`, but how does it work for binaries that vendor and use controller-tools as a library?

If I understand correctly, the version that gets inserted will be the version of _that_ binary, not the version of the underlying controller-tools library that the binary depends on.

In `operator-sdk`, we're currently using controller-tools as a library, so it seems like this would result in the `operator-sdk` version ending up in that annotation.

I'm curious if there's an improvement we could make here. A couple of options I have in mind are:
1. Somehow make that version actually reflect the version of controller-tools.
2. Make the annotation key overridable such that it can be changed in scenarios where `controller-tools` is used as a library.

**Comment by DirectXMan12** [comment]
> Somehow make that version actually reflect the version of controller-tools.

The traditional method is to use linker flags, but that doesn't provide a good answer with go get.  The other option is manual updates, but that's also not great.

I *think* we can probably traverse the dependencies in the debug info if the main module doesn't look like controller-gen -- that's probably the most reliable method here.

> Make the annotation key overridable such that it can be changed in scenarios where controller-tools is used as a library.

That could work, but defeats the purpose a bit (determine usage of particular features to get a good idea how much particular features are used).
