### ISSUE TITLE
"Error: no generators specified" conflicts with cli help

### ISSUE THREAD

**Issue by pgier** [kubernetes-sigs/controller-tools#363]
The controller-gen cli help print this example
```
    # Run all the generators for a given project
    controller-gen paths=./apis/...
```
But running this command fails with the error message `Error: no generators specified`.  I'm guessing the cli help is wrong, or should this run all the generators?

**Comment by JohnStarich** [comment]
Looks like I’m 1 day too late...

Anyone know how to run all generators? Was that option removed after v0.1?

**Comment by Jont828** [comment]
I'm having the same issue, unfortunately.
