### ISSUE TITLE
controller-gen doesn't work on mac

### ISSUE THREAD

**Issue by TommyLike** [kubernetes-sigs/controller-tools#367]
**environment**:
1. system os: mac catalina 10.15
2. controller-gen: Version: v0.2.4
3. go: go version go1.12.6 darwin/amd64

**Error**:
```
controller-gen object:headerFile=./hack/boilerplate.go.txt paths="./..."
Error: go [list -e -json -compiled=true -test=false -export=false -deps=true -find=false -tags ignore_autogenerated -- ./...]: exit status 2: # runtime/cgo
clang: error: unable to find utility "clang", not a developer tool or in PATH
```
**background**:
I created a new operator project with kubebuilder init command, but it failed to execute the make generate command which is generated by the framework on macos.

**Comment by DirectXMan12** [comment]
You're missing a C compiler, which is required to work with cgo.  Install the dev tools for your system.
