### ISSUE TITLE
Generating CRD with a validation pattern fails

### ISSUE THREAD

**Issue by aeb-sia** [kubernetes-sigs/controller-tools#369]
When I try to generate a CRD with the validation pattern 
```
// +kubebuilder:validation:Pattern=^https?:\/\/.+$
```
set on a field, it keeps failing. I found out that the issue is the `:`

It must be a sort of recent change, since the pattern used to work fine. I updated go and the operator-sdk lately. I suspect this pulled a couple of updates that broke things

I'm using the `operator-sdk version: "v0.12.0", commit: "2445fcda834ca4b7cf0d6c38fba6317fb219b469", go version: "go1.13.3 linux/amd64"`

I can run `operator-sdk generate k8s` fine, but when I try `operator-sdk generate openapi` I get an this error:
```
 $ operator-sdk generate openapi --verbose
DEBU[0000] Debug logging is set                         
INFO[0000] Running OpenAPI code-generation for Custom Resource group versions: [next:[v1alpha1], ] 
Error: error generating CRD for Group next Version v1alpha1 Kind NextAppSet
Usage:
  operator-sdk generate openapi [flags]

Flags:
  -h, --help   help for openapi

Global Flags:
      --verbose   Enable verbose logging
```

The funny thing is, it complains about an error in `NextAppSet` but the validation pattern is defined in another crd.

I guess it's the fault of this package, but my knowledge about that is pretty limited, so I might be wrong.

I'm using `go version go1.13.4 linux/amd64`

and my go.mod looks like this
```
go 1.13

require (
	github.com/go-logr/logr v0.1.0
	github.com/go-openapi/spec v0.19.0
	github.com/operator-framework/operator-sdk v0.12.0
	github.com/spf13/pflag v1.0.3
	k8s.io/api v0.0.0
	k8s.io/apimachinery v0.0.0
	k8s.io/client-go v11.0.0+incompatible
	k8s.io/kube-openapi v0.0.0-20190918143330-0270cf2f1c1d
	sigs.k8s.io/controller-runtime v0.3.0
)

// Pinned to kubernetes-1.15.4
replace (
	k8s.io/api => k8s.io/api v0.0.0-20190918195907-bd6ac527cfd2
	k8s.io/apiextensions-apiserver => k8s.io/apiextensions-apiserver v0.0.0-20190918201827-3de75813f604
	k8s.io/apimachinery => k8s.io/apimachinery v0.0.0-20190817020851-f2f3a405f61d
	k8s.io/apiserver => k8s.io/apiserver v0.0.0-20190918200908-1e17798da8c1
	k8s.io/cli-runtime => k8s.io/cli-runtime v0.0.0-20190918202139-0b14c719ca62
	k8s.io/client-go => k8s.io/client-go v0.0.0-20190918200256-06eb1244587a
	k8s.io/cloud-provider => k8s.io/cloud-provider v0.0.0-20190918203125-ae665f80358a
	k8s.io/cluster-bootstrap => k8s.io/cluster-bootstrap v0.0.0-20190918202959-c340507a5d48
	k8s.io/code-generator => k8s.io/code-generator v0.0.0-20190612205613-18da4a14b22b
	k8s.io/component-base => k8s.io/component-base v0.0.0-20190918200425-ed2f0867c778
	k8s.io/cri-api => k8s.io/cri-api v0.0.0-20190817025403-3ae76f584e79
	k8s.io/csi-translation-lib => k8s.io/csi-translation-lib v0.0.0-20190918203248-97c07dcbb623
	k8s.io/kube-aggregator => k8s.io/kube-aggregator v0.0.0-20190918201136-c3a845f1fbb2
	k8s.io/kube-controller-manager => k8s.io/kube-controller-manager v0.0.0-20190918202837-c54ce30c680e
	k8s.io/kube-proxy => k8s.io/kube-proxy v0.0.0-20190918202429-08c8357f8e2d
	k8s.io/kube-scheduler => k8s.io/kube-scheduler v0.0.0-20190918202713-c34a54b3ec8e
	k8s.io/kubelet => k8s.io/kubelet v0.0.0-20190918202550-958285cf3eef
	k8s.io/legacy-cloud-providers => k8s.io/legacy-cloud-providers v0.0.0-20190918203421-225f0541b3ea
	k8s.io/metrics => k8s.io/metrics v0.0.0-20190918202012-3c1ca76f5bda
	k8s.io/sample-apiserver => k8s.io/sample-apiserver v0.0.0-20190918201353-5cc279503896
)
```

**Comment by aeb-sia** [comment]
I don't think this is fixed yet, is it?

**Comment by hypnoglow** [comment]
@aeb-sia Could you try enclose pattern with a backtick:
```
+kubebuilder:validation:Pattern=`^https?:\/\/.+$`
```

This worked for me:

In go struct:

```go
	// +kubebuilder:validation:Pattern=`^https?:\/\/.+$`
	Remote string `json:"remote,omitempty"`
```

Generated:
```yaml
          properties:
            remote:
              pattern: ^https?:\/\/.+$
              type: string
```

**Comment by aeb-sia** [comment]
Yes that works. Is this escaping documented somewhere?

**Comment by hypnoglow** [comment]
@aeb-sia I am not sure if this is documented somewhere. I've found the example in the [testdata](https://github.com/kubernetes-sigs/controller-tools/blob/v0.2.5/pkg/crd/testdata/cronjob_types.go#L114).

The [documentation](https://book.kubebuilder.io/reference/markers.html?highlight=quot#marker-syntax) I've found so far only states this:

> For convenience, in simple cases the quotes may be omitted from strings, although this is not encouraged for anything other than single-word strings:
>
> // +kubebuilder:validation:Type=string

I guess we need some help here to improve documentation on this, describing HOW to quote and why some characters need extra treatment (i.e. what characters must be escaped).
