### ISSUE TITLE
duplicate marker: XPreserveUnknownFields vs PreserveUnknownFields

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-sigs/controller-tools#380]
@sttts did you intend to have have preserveunknownfields registered as both `kubebuilder:validation:XPreserveUnknownFields` and `kubebulder:pruning:PreserveUnknownFields` (field only)?

I seem to recall that only the latter was desired.

**Comment by sttts** [comment]
I think the later only.

**Comment by jiachengxu** [comment]
remove-lifecycle stale

**Comment by jiachengxu** [comment]
Hi @DirectXMan12 , the PR was created half year ago: #422,  can you please take a look?

**Comment by DirectXMan12** [comment]
ah, I think I somehow missed the pr, sorry about that :-/
