### ISSUE TITLE
How to skip/ignore specific type?

### ISSUE THREAD

**Issue by ZedYeung** [kubernetes-sigs/controller-tools#383]
I have an interface type in my file like this.
```
type SomeInterface interface {
	someFunction() *string
	OtherFunction() SomeInterface
}
```
Since the interface is not supported. https://github.com/kubernetes-sigs/controller-tools/pull/126
The error would be `unsupported AST kind *ast.InterfaceType`

Any way to skip such type with marker like `kubebuilder:skipversion`

I tried this 
```
// +kubebuilder:skipversion
type SomeInterface interface {
	someFunction() *string
	OtherFunction() SomeInterface
}
```
but not work. 
Is this the right way to use it? what is the version it skip? should i pass the version as argument? I cannot find any document or test case using this. 
Thanks.

**Comment by CermakM** [comment]
Any reaction would be nice...

**Comment by spolti** [comment]
Is there any solution for this?

/reopen
