### ISSUE TITLE
Rethinking metadata schema generation in CRD yamls

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/controller-tools#385]
Currently controller-tools does not generate any properties for metadata fields at any level in CRD yamls to accommodate for structural schema.

https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/crd/known_types.go#L29-L33

My it is my understanding that only top level metadata field is restricted to define name & generatedName fields. Any other nested metadata field can have detailed schema. Some common cases are embedding PodTemplate, PersistentVolumeClaim in CRDs.

Currently we are creating our own `ObjectMeta` types are using them in our CRDs to work around this issue. 

Do you think controller-tools could just strip the properties for top level metadata field? One way to do that will be to remove `ObjectMeta` from known types and then clean the generated yaml before writing to disk.

Any thoughts?

**Comment by tamalsaha** [comment]
/sig api-machinery

cc: @sttts @munnerz @DirectXMan12

**Comment by sttts** [comment]
I would prefer to see a stripped down EmbeddedObjectMeta if possible, or at least let controller-gen do the restriction. ObjectMeta has so many fields which do not make sense for embedded ObjectMeta. Also the schema is super huge.

**Comment by tamalsaha** [comment]
I like the idea of `EmbeddedObjectMeta`. We kind of doing that in our custom type. https://github.com/kmodules/offshoot-api/blob/master/api/v1/pvc.go#L24-L98

**Comment by DirectXMan12** [comment]
I think #395 is actually close to being mergable, it's just a bit out of date.  If someone wants to pick that up, I've left comments on it.

**Comment by sttts** [comment]
@DirectXMan12 see my comment in 395. IMO we should not do that. Instead let's add a sensible EmbeddedObjectMeta to API machinery and make controller-tools warn if that is not used instead of ObjectMeta.

**Comment by DirectXMan12** [comment]
@sttts that doesn't work for when you embed things with ObjectMeta in them already though -- e.g. PodTemplateSpec, which is probably the most common case.  We'd have to swap that out on demand or something.

**Comment by sttts** [comment]
True. So we must add special handling for embedded ObjectMeta to only specifiy sensible fields (more than just `type: object` but considerably less than a full ObjectMeta. It's ugly. As written in the other issue: sin of the past :-/

**Comment by EronWright** [comment]
For posterity: if you're developing a CRD with a spec field that uses `corev1.PodTemplate`, add the `generateEmbeddedObjectMeta=true` option to your makefile as shown here: https://github.com/openshift/boilerplate/pull/291

This will ensure that your CRD has a schema for `ObjectMeta`, so that your users may apply labels/annotations to the pod.
