### ISSUE TITLE
Avoid generating description in metadata of CRD structural schema

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/controller-tools#386]
CRD structural schema requires that `if metadata is specified, then only restrictions on metadata.name and metadata.generateName are allowed.`

If I add comments to `metadata` field in Go struct, kubebuilder sets that as `metadata.description` in the generated CRd yaml. This generated yaml is considered invalid as structural schema.

Example:
- https://github.com/appscode/voyager/commit/5f8a169dae4eb73738ec965575328177026bf4b9#diff-621dd318cc94d163f872e0712dc053a8L47-L48
- https://github.com/appscode/voyager/commit/5f8a169dae4eb73738ec965575328177026bf4b9#diff-c793f5d116450276c7d0a4cb7e90b538L49

I wonder if controller-tools can avoid generating metadata.description at all times?

**Comment by tamalsaha** [comment]
/sig api-machinery

cc: @sttts @DirectXMan12 @munnerz 

xref: https://github.com/kubernetes/kubernetes/issues/86800

**Comment by sttts** [comment]
Please create a PR for controller-gen which avoid the description field. We cannot change the CRD restriction, but only adapt controller-gen to follow it.
