### ISSUE TITLE
pkg/apis/... tests don't compile after adding a second time

### ISSUE THREAD

**Issue by pwittrock** [kubernetes-sigs/controller-tools#39]
The test name for each api is `TestStorage` so when we create 2 apis in the same package their names conflict.

**Comment by droot** [comment]
@Liujingfang1 Can you pl. take a look it ?

**Comment by Liujingfang1** [comment]
@droot Yes, will look into it.

**Comment by Liujingfang1** [comment]
We can add the kind name to this function. It will become `TestStorage<Kind>`. @droot @pwittrock What do you think?
