### ISSUE TITLE
controller-gen: no errors for a CRD with multiple versions marked as storage

### ISSUE THREAD

**Issue by estroz** [kubernetes-sigs/controller-tools#390]
**controller-tools version:** `v0.2.4`

I have two API versions `./api/v1alpha1` and `./api/v1alpha2` for my kind `Frigate` and group `example.com` in a kubebuilder operator project. Upon running
```console
controller-gen crd paths="./..." output:crd:artifacts:config="config/crd/bases"
```
I see the following:
1. An absence of `+kubebuilder:storageversion` above either `Frigate` type declaration will result in an error.
1. Setting `+kubebuilder:storageversion` above either `Frigate` type declaration but not both will produce a CRD manifest with `storage: true` under the correct version.
1. Setting `+kubebuilder:storageversion` above _both_ `Frigate` type declarations will produce a CRD manifest with `storage: true` under _both_ versions.

I would expect an error to be returned in case `3` since only one CRD version can be a storage version.

/cc @DirectXMan12 @droot @pwittrock

**Comment by DirectXMan12** [comment]
/kind bug
/priority important-longterm
/good-first-issue

yep, we should check that only one is marked storage version

**Comment by estroz** [comment]
I'll take this on.
