### ISSUE TITLE
Controller-gen creating unwanted CRDs

### ISSUE THREAD

**Issue by thackem** [kubernetes-sigs/controller-tools#398]
In my API structs I have a spec field like:
```
type MyObjectSpec struct {
	Live bool `json:"live,omitempty"`
	ComplexRef ObjectRef `json:"object,omitempty"`
	SimpleRef *v1.LocalObjectReference `json:"configMapRef"`
}

// no kubebuilder annotation here

type ObjectRef struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Foo string `json:"foo"`
}
```

This results in an ObjectRef CRD file being generated in config/crd/bases when I run the default `make generate` target.

**Comment by DirectXMan12** [comment]
/kind feature
/priority important-longterm

/help

this should prob just be a marker to disable this that we can read in `gen.go`

**Comment by zroubalik** [comment]
any update on this please?

**Comment by DirectXMan12** [comment]
I think you should be able to use the `skipversion` marker here.

**Comment by zroubalik** [comment]
@DirectXMan12 but this marker disable CRD generation for all types in the particular version, right?
For example I have `MyTypeA`, `MyTypeB` and `InternalTypeA` in version `v1alpha1` and I'd like to generate CRDs only for `MyTypeA` and `MyTypeB`, not for `InternalTypeA`.
Unfortunately I haven't found a way how to achieve that.
