### ISSUE TITLE
Remove creationTimestamp from generated CRD

### ISSUE THREAD

**Issue by pgier** [kubernetes-sigs/controller-tools#402]
controller-gen currently adds the metadata field `creationTimestamp: null`.  I think this field should not be included in the CRD yaml since this value should be added by the server.

**Comment by uthark** [comment]
I did some digging and found out that this comes from JSON encoding.
What happens is that `yaml.Marshal` is called https://github.com/uthark/controller-tools/blob/master/pkg/genall/genall.go#L106.
This in turn calls `json.Marshal` https://github.com/kubernetes-sigs/yaml/blob/v1.1.0/yaml.go#L17 
and it falls to the `	if f.omitEmpty && isEmptyValue(fv)` check (https://golang.org/src/encoding/json/encode.go, line 747) and isEmptyValue returns false for empty `meta.v1.Time` (https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/time.go#L33-L35)

So, not sure this is easily fixable in this repo. (I'm not a maintainer, but was stumbling over the same issue)

**Comment by erikgb** [comment]
Thanks for the nice "digging" @uthark! I am experiencing this issue too, after operator-sdk migrated to kubebuilder. Since this happens to both generated YAML-files, CRD and operator Role, I think you are right that this a general issue with the YAML marshalling. Any ideas on how/where this issue can be resolved? It is a bit annoying to have to modify the generated files.....

**Comment by erikgb** [comment]
Probable root cause https://github.com/kubernetes/kubernetes/issues/86811, and potential local fix: https://github.com/kubernetes/kubernetes/issues/86811#issuecomment-588276966.

**Comment by camilamacedo86** [comment]
remove-lifecycle stale

**Comment by shaneutt** [comment]
It seems like this is still an issue, how do we feel about re-opening this?

**Comment by pg-yang** [comment]
/reopen



> It seems like this is still an issue, how do we feel about re-opening this?

This issue still exists, How about removing all `nil` fields from `jsonObj `, it's safe.

https://github.com/kubernetes-sigs/controller-tools/blob/73391d1c6f3edfed27bbd82c8cc7bfb05f635bad/pkg/genall/genall.go#L181
