### ISSUE TITLE
go get controller-gen@v0.2.5: invalid version

### ISSUE THREAD

**Issue by Kyrremann** [kubernetes-sigs/controller-tools#406]
I'm trying to download the latest version of `controller-gen`, but get `invalid version` for every version i try. I'm guessing I'm doing something wrong on my side, but not sure how to fix it.

```
$ go get github.com/controller-tools/cmd/controller-gen@v0.2.5
go: finding github.com v0.2.5
go: finding github.com/controller-tools/cmd/controller-gen v0.2.5
go: finding github.com/controller-tools/cmd v0.2.5
go: finding github.com/controller-tools v0.2.5
go: finding github.com/controller-tools/cmd v0.2.5
go: finding github.com/controller-tools/cmd/controller-gen v0.2.5
go get github.com/controller-tools/cmd/controller-gen@v0.2.5: github.com/controller-tools/cmd/controller-gen@v0.2.5: invalid version: unknown revision controller-gen/v0.2.5
```

Running `go version go1.13.4 darwin/amd64`.

**Comment by pgier** [comment]
Your command is missing part of the repo path:

> $ go get github.com/controller-tools/cmd/controller-gen@v0.2.5

Should be:

> $ go get github.com/kubernetes-sigs/controller-tools/cmd/controller-gen@v0.2.5

However, this command will tell you that the github repo path doesn't match the declared module path, so what you really want is the `sigs.k8s.io` path to install the command.

```
$ go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.5
```

**Comment by Kyrremann** [comment]
Thanks! That solved!
