### ISSUE TITLE
Support generating Kustomize friendly annotation for CRDs

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/controller-tools#410]
https://kubectl.docs.kubernetes.io/pages/examples/kustomize.html

```
# Each entry in this list should be a relative path to
# a file for custom resource definition(CRD) in openAPI definition.
#
# The presence of this field is to allow kustomize be
# aware of CRDs and apply proper
# transformation for any objects in those types.
#
# Typical use case: A CRD object refers to a ConfigMap object.
# In kustomization, the ConfigMap object name may change by adding namePrefix, nameSuffix, or hashing
# The name reference for this ConfigMap object in CRD object need to be
# updated with namePrefix, nameSuffix, or hashing in the same way.
#
# The annotations can be put into openAPI definitions are:
#   "x-kubernetes-annotation": ""
#   "x-kubernetes-label-selector": ""
#   "x-kubernetes-identity": ""
#   "x-kubernetes-object-ref-api-version": "v1",
#   "x-kubernetes-object-ref-kind": "Secret",
#   "x-kubernetes-object-ref-name-key": "name",
crds:
- crds/typeA.json
- crds/typeB.json
```

**Comment by MariusSchiffer** [comment]
I think this is still a useful thing.

Example: A CRD uses `PodTemplate`, which contains `configMapRef`. This reference will not be updated by kustomize for the `configMapGenerator` as it cannot see that this is a configMap reference.

/reopen

**Comment by sbueringer** [comment]
I don't get it. What is the concrete ask here? Can you give an example what exactly controller-gen could support here?

**Comment by MariusSchiffer** [comment]
controller-gen should add `x-kubernetes-object-ref-kind` and `x-kubernetes-object-ref-api-version` to the generated  CRD schema for core kubernetes objects (or all).
This allows kustomize (and maybe other tools) to know where to find the object definition.  
An example why this is useful is kustomize's `configMapGenerator` feature.  
When kustomize generates a configMap, it replaces all mentions of this configMap in `configMapRef` with the generated name. But this only works if kustomize correctly recognizes it as a `configMapRef`. For this, during CRD loading, it checks `x-kubernetes-object-ref-kind`, see here: https://github.com/kubernetes-sigs/kustomize/blob/880a7a0187f0cb34132baa706d4a48d1ef5b8912/api/internal/accumulator/loadconfigfromcrds.go#L163

Here is an example: https://github.com/kubernetes-sigs/kustomize/issues/681#issuecomment-454181149

For another concrete example, elastic's cloud-on-k8s has CRDs which includes `podTemplate` (directly included from kubernetes definitions). Same problem that kustomize cannot recognize the `podTemplate`.

Definitions here: https://github.com/elastic/cloud-on-k8s/blob/main/pkg/apis/beat/v1beta1/beat_types.go#L96
Output here: https://github.com/elastic/cloud-on-k8s/blob/main/config/crds/v1/resources/beat.k8s.elastic.co_beats.yaml#L89

They actually remove everything below `podTemplate` as duplicating core kubernetes CRD parts becomes large quickly: https://github.com/elastic/cloud-on-k8s/blob/main/config/crds/v1/patches/beat-patches.yaml#L3

I'm not sure if this is the best approach (I feel like there could be something more native-y than using a `x-` property).  
It also looks like this would require changing `JSONSchemaProps`.

**Comment by JoelSpeed** [comment]
If I've read this correctly, you would need to re-ignite https://github.com/kubernetes/kubernetes/issues/82942 and get this support into Kube as part of the CRD apiextensions-apiserver before changing anything in controller-tools.

JSONSchemaProps relates to a Kubernetes API, it's not part of this repo, we cannot just change it, and expect it to work

**Comment by MariusSchiffer** [comment]
After some searchin I found more on kustomize's side, so this has to be solved there: https://github.com/kubernetes-sigs/kustomize/issues/3418
