### ISSUE TITLE
contoller-gen: webhook generator support for admissionregistration.k8s.io/v1

### ISSUE THREAD

**Issue by jiachengxu** [kubernetes-sigs/controller-tools#419]
Hi folks,
Since `admissionregistration.k8s.io/v1beta1` is deprecated in kubernetes v1.16 in favor of `admissionregistration.k8s.io/v1`, do you have a plan for adding support to generate webhook configurations (Validating/MutatingWebhokConfiguration) for `admissionregistration.k8s.io/v1`?

I can work on this if it is needed.

**Comment by aborilov** [comment]
+1

**Comment by vincepri** [comment]
This would be good to have, @DirectXMan12 @alvaroaleman thoughts?

**Comment by jiachengxu** [comment]
I think we can add a `WebhookVersions` to Webhook generator, just like what we have for CRD generator (CRDVersions): https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/crd/gen.go#L81
WDYT @vincepri ?

**Comment by vincepri** [comment]
Not sure if we have to support both of them going forward, we can make this a breaking(?) change and only generate v1 webhooks

**Comment by alvaroaleman** [comment]
> Not sure if we have to support both of them going forward, we can make this a breaking(?) change and only generate v1 webhooks

Not sure if completely removing the beta support is a good idea because some cloud vendors severly lack behind in the offered kube version. What kube version is needed for the v1 webhook?

Defaulting to the newer version sgtm though

**Comment by jiachengxu** [comment]
> Not sure if completely removing the beta support is a good idea because some cloud vendors severly lack behind in the offered kube version. What kube version is needed for the v1 webhook?

@alvaroaleman as mentioned here: https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#prerequisites
`admissionregistration.k8s.io/v1` is only available with kubernetes v1.16+

@vincepri I also think it is better to also have v1beta1 webhook, and we default to generate the `v1` version.
