### ISSUE TITLE
Flaky behaviour using custom slice types and listType marker

### ISSUE THREAD

**Issue by avorima** [kubernetes-sigs/controller-tools#435]
`controller-gen` will sometimes fail to create the CRD manifests when using a custom slice type, e.g. `type Foos []Foo` and the `listType` and `listMapKey` markers.

To reproduce this create a sample project with kubebuilder v2.3.1:
```
kubebuilder init --repo temp
kubebuilder create api --group ship --version v1beta1 --kind Frigate
```

and then add the following to the `api/v1beta1/frigate_types.go` file:

```go
// FrigateStatus defines the observed state of Frigate
type FrigateStatus struct {
        // +kubebuilder:validation:Type=array
        // +optional
        // +listType=map
        // +listMapKey=type
        Conditions Conditions `json:"conditions,omitempty"`
}

type Conditions []Condition

type Condition struct {
        Type   string `json:"type,omitemtpy"`
        Status string `json:"status,omitempty"`
}
```

Running `make manifests` will then on occasion yield the following errors:

```
/tmp/test/api/v1beta1/frigate_types.go:35:2: must apply listType to an array
/tmp/test/api/v1beta1/frigate_types.go:35:2: must apply listMapKey to an associative-list
```

If the `+kubebuilder:validation:Type=array` marker is above the type definition it fails consistently.

I have verified that this occurs with both `v0.2.5` and `v0.3.0`.

The issue seem to come the fact that both [`listType`](https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/crd/markers/topology.go#L114) and [`kubebuilder:validation:Type`](https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/crd/markers/validation.go#L324) markers implement `ApplyFirst` to ensure they get applied before all other markers. But since [applyMarkers](https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/crd/schema.go#L111) loops over a map, the order is random.

**Comment by avorima** [comment]
This issues still is present in 0.6.0

/reopen

**Comment by chrischdi** [comment]
/repoen

The issue is still reproducible on the latest commit (`529c857f74b225412836567200cd0ae003fbb3b3`).

In my case I just want to add the two markers `+listType=map` and `+listMapKey=id` to allow the slice to get used together with Server-Side Apply.

In fact, when using a custom slice type it is not even possible to add the two markers.

The following variant simply get ignored by `controller-gen`:
```go
type BarSpec struct {
  Foos Foos `json:"foos,omitempty"`
}

// +listType=map
// +listMapKey=id
type Foos []Foo

type Foo struct {
	ID    string `json:"id"`
	Other string `json:"other"`
}
```

The following variant leads to an error similar as in the first comment, when running `make manifests`:

```go
type BarSpec struct {
	// +listType=map
	// +listMapKey=id
	Foos Foos `json:"foos,omitempty"`
}

type Foos []Foo

type Foo struct {
	ID    string `json:"id"`
	Other string `json:"other"`
}
```

The error:
```
❯ make manifests
/tmp/test-ct/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/tmp/test-ct/api/v1beta1/bar_types.go:30:2: must apply listType to an array, found
/tmp/test-ct/api/v1beta1/bar_types.go:30:2: must apply listMapKey to an array, found
Error: not all generators ran successfully
run `controller-gen rbac:roleName=manager-role crd webhook paths=./... output:crd:artifacts:config=config/crd/bases -w` to see all available markers, or `controller-gen rbac:roleName=manager-role crd webhook paths=./... output:crd:artifacts:config=config/crd/bases -h` for usage
make: *** [manifests] Error 1
```
