### ISSUE TITLE
Support for array length in printcolumn

### ISSUE THREAD

**Issue by andrewrynhard** [kubernetes-sigs/controller-tools#447]
Hello, I would like to have a printcolumn that disaplays the length of an array in the status. In the jsonpath docs this looks like it is possible. I either have the syntax wrong, or it is not supported.

running

```
kubectl get x -o=jsonpath='{.status.y.length()}'
```

gives me nothing.

**Comment by Wazbat** [comment]
Was this feature ever implemented? This would be very useful

**Comment by panpan0000** [comment]
same question here

**Comment by paullaffitte** [comment]
I need this feature too

**Comment by cristiansteib** [comment]
Also, I need this feature

**Comment by sbueringer** [comment]
Hm. Not sure if this is something that can be fixed by generating the CRD differently. You should probably talk to kubectl folks.
