### ISSUE TITLE
Cut new release

### ISSUE THREAD

**Issue by Jeffwan** [kubernetes-sigs/controller-tools#453]
controller-tools has lots of improvement we'd like to use and it's been a while since 0.3.0 release.

Can you help cut a new release?

**Comment by vincepri** [comment]
We're currently blocked on #352 and https://github.com/kubernetes-sigs/controller-tools/pull/501#discussion_r501314502, I haven't had time to implement any of these changes yet, maybe I could carve out something for next week. If you folks are able to pick up that bit about webhooks and we can merge 501, that'd be really appreciated :)
