### ISSUE TITLE
controller-gen unable to set file headers

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes-sigs/controller-tools#464]
This I believe is a feature request.  It would be awesome to have controller-gen output file headers when you generate yaml files with the clip. When generating go code you are able to set a header file, but when you generate yaml it seems that does not work.

When providing the following options the yaml files do not contain a header.

```
controller-gen object:headerFile=./hack/boilerplate/boilerplate.yaml.txt rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
```

Maybe I am missing something.

**Comment by coro** [comment]
I'd agree with this, would love to see this feature. We have a requirement to include license NOTICE headers in even our generated YAML, and this would allow us to perform this without manually injecting it after every run of `controller-gen`.

**Comment by justinsb** [comment]
/reopen

Should we turn off the robot?
