### ISSUE TITLE
Custom JSON marshaling causes schema validation generation to be skipped

### ISSUE THREAD

**Issue by christarazi** [kubernetes-sigs/controller-tools#466]
I have a CRD type as follows:

```golang
type A struct {
  metav1.TypeMeta
  metav1.TypeMeta

  Spec   Spec
  Status Status
}
```

The `Spec` field implements custom JSON marshaling. This causes the validation schema generation for `Spec` to be skipped, and replaced with `type: Any`. This is due to https://github.com/kubernetes-sigs/controller-tools/pull/427. 

I expect to control this with a marker, or a similar knob. In this case, an opt-out marker makes sense if https://github.com/kubernetes-sigs/controller-tools/pull/427 implements sane default behavior.

**Comment by alvaroaleman** [comment]
We've reverted #427 in #505 as `type: Any` is not valid.
/close

Feel free to re-open if you think the revert doesn't address the issue.
