### ISSUE TITLE
controller-gen tries to generate DeepCopy functions for interface types

### ISSUE THREAD

**Issue by dionysius** [kubernetes-sigs/controller-tools#471]
I'm coming from kubebuilder

To reduce amount of code to write and thus complexity I want to use interface types so different objects can benefit from the same validation in the webhook.

I defined the following interface for a Resource (this example is very simplified):
```
type ClusterDefinition struct {
	// Identifier of the cluster
	// +kubebuilder:validation:Required
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

type Identifier interface {
	Get() string
}

func (c *ClusterDefinition) Get() string {
	return c.Name
}
```

controller-gen outputs the following autogenerated DeepCopy functions:
```
// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Identifier) DeepCopyInto(out *Identifier) {
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetaName.
func (in *Identifier) DeepCopy() *Identifier {
	if in == nil {
		return nil
	}
	out := new(Identifier)
	in.DeepCopyInto(out)
	return out
}
```

resulting into the error:
```
$ controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
.../some-ctrl/apis/group/v1:-: invalid type interface{Get() string}
```

The error doesn't seem to be helpful.

The problem is, that controller-gen should not define DeepCopy functions for interface types. You can't deepcopy an interface, since it doesn't hold values like the struct type. The controller does correctly compile without the Deepcopy functions:

```
$ go build -o bin/manager main.go
<no error>
```

Can't we just ignore interface types in the controller-gen? There's no need to generate anything based on them.

**Comment by jiachengxu** [comment]
You can use this marker: `+kubebuilder:object:generate=<bool>` to enable/disable deepcopy for objects/interfaces.
ref: https://book.kubebuilder.io/reference/markers/object.html

**Comment by dionysius** [comment]
Ooooh, RTFM :D

There are two markers with same name, but one is for the type, the other for the package

**Comment by goder-tao** [comment]
> You can use this marker: `+kubebuilder:object:generate=<bool>` to enable/disable deepcopy for objects/interfaces. ref: https://book.kubebuilder.io/reference/markers/object.html

Thanks! It works! save my life!
