### ISSUE TITLE
+kubebuilder:default throws "Forbidden: must not be set" error

### ISSUE THREAD

**Issue by chungktran** [kubernetes-sigs/controller-tools#478]
Using `// +kubebuilder:default=50` throws `Forbidden: must not be set` error when executing `make install`. It does generate the CRD `default: 50` in the CRD but when installing it using `make install` that error is thrown. Full error below.

```
$ make install
/home/ctran/Projects/go/bin/controller-gen "crd:trivialVersions=true" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
kustomize build config/crd | kubectl apply -f -
The CustomResourceDefinition "sample.example.com" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[pollingInterval].default: Forbidden: must not be set
make: *** [Makefile:30: install] Error 1
```

Kubebuilder version: `Version: version.Version{KubeBuilderVersion:"2.3.1", KubernetesVendor:"1.16.4", GitCommit:"8b53abeb4280186e494b726edf8f54ca7aa64a49", BuildDate:"2020-03-26T16:42:00Z", GoOs:"unknown", GoArch:"unknown"}`

**Comment by npiganeau** [comment]
I had the same issue when installing apiextensions.k8s.io/v1beta1 CRD.

Switching to apiextensions.k8s.io/v1 CRD solved the issue for me, by changing the Makefile and adding `crd:trivialVersions=true,crdVersions=v1` in the CRD Options:

```
controller-gen "crd:trivialVersions=true,crdVersions=v1" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
```

**Comment by chungktran** [comment]
Thanks @npiganeau. I'll give this a try and see.

**Comment by camilamacedo86** [comment]
Hi Folks, could you please address it in a FAQ section of the docs?
