### ISSUE TITLE
+kubebuilder:validation:Required/Optional does nothing

### ISSUE THREAD

**Issue by chungktran** [kubernetes-sigs/controller-tools#479]
Using `// +kubebuilder:validation:Required` or `// +kubebuilder:validation:Optional` on `package` or `field` does nothing. After adding the markers I did `make manifests` but nothing changed in the CRD. I was still able to create CR that have missing required fields.

Kubebuilder version: `Version: version.Version{KubeBuilderVersion:"2.3.1", KubernetesVendor:"1.16.4", GitCommit:"8b53abeb4280186e494b726edf8f54ca7aa64a49", BuildDate:"2020-03-26T16:42:00Z", GoOs:"unknown", GoArch:"unknown"}`

**Comment by alkar** [comment]
Is it likely the fields have `omitempty` in their json tags? Can you share the type(s)?

**Comment by chungktran** [comment]
@alkar Yes you are correct. So `omitempty` should not be in the tag if that annotation is to be used?

**Comment by alkar** [comment]
I noticed this myself while struggling to understand how the markers work.
See here https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/crd/schema.go#L369

It seems that the `omitempty` json tag implies an optional field.

**Comment by chungktran** [comment]
Thanks. I'll test it out and let you know.

**Comment by chungktran** [comment]
@alkar Thanks for the tip. Removing `omitempty` work as expected.
