### ISSUE TITLE
Controller-gen doesn't intepreate "string" json tag

### ISSUE THREAD

**Issue by xpivarc** [kubernetes-sigs/controller-tools#507]
Given this struct
```
type Something struct {
	SomeAtrribute int               `json:"someAtrribute,string,omitempty"`
}
```
the validation schema will be as 
```
someAtrribute:
   type: integer
```
and all requests with this field set will fail.

**Comment by cbandy** [comment]
Perhaps you want [intstr.IntOrString](https://pkg.go.dev/k8s.io/apimachinery/pkg/util/intstr#IntOrString)?

**Comment by xpivarc** [comment]
> Perhaps you want [intstr.IntOrString](https://pkg.go.dev/k8s.io/apimachinery/pkg/util/intstr#IntOrString)?

IMO it is not the same as using types with "string". You want the convenience of `int` but API representation of `string`. Furthermore, [openapi-gen](https://github.com/kubernetes/kube-openapi/tree/master/cmd/openapi-gen) treats this as this PR and inconsistencies could cause problems.
