### ISSUE TITLE
Building private/dev controller-gen binary

### ISSUE THREAD

**Issue by champak** [kubernetes-sigs/controller-tools#509]
Hi Folks,
I wanted to experiment with some changes to controller-gen and use with kubebuilder and did not see a Makefile or target to build a local controller-gen executable. I built it with e.g.
.. GO111MODULE=on go build -a -o mygen cmd/controller-gen/main.go
etc.

and then to use with kubebuilder put the binary on path to avoid the go get fetch in the kubebuilder makefile.

Is there a better way to do this ? I am guessing others have needed to experiment with changes and there is probably a better way to get a local binary.  Thanks for any comments.

**Comment by prashao** [comment]
@champak - See my answer to issue #520
