### ISSUE TITLE
go get fails with JSONSchemaProps has no field or method XMapType

### ISSUE THREAD

**Issue by michalrabinowitch** [kubernetes-sigs/controller-tools#512]
running 
`go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.4.0`
 results in:
`go: found sigs.k8s.io/controller-tools/cmd/controller-gen in sigs.k8s.io/controller-tools v0.4.0
  sigs.k8s.io/controller-tools/pkg/crd/markers
../../../../pkg/mod/sigs.k8s.io/controller-tools@v0.4.0/pkg/crd/markers/topology.go:137:8: schema.XMapType undefined (type *"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1".JSONSchemaProps has no field or method XMapType)
../../../../pkg/mod/sigs.k8s.io/controller-tools@v0.4.0/pkg/crd/markers/topology.go:152:8: schema.XMapType undefined (type *"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1".JSONSchemaProps has no field or method XMapType)`

go verion:
`go version go1.15.3`

**Comment by takirala** [comment]
+1, i am facing the same issue

**Comment by DirectXMan12** [comment]
do you have an older version of some k8s dependency pinned in go.mod for your project?  Usually, we reccomend putting controller-tools in a separate mini-module for tooling just for this reason.

**Comment by takirala** [comment]
@DirectXMan12 thanks, I do have pinned deps. Upgrading them resolved the issue.

> we reccomend putting controller-tools in a separate mini-module

can you elaborate on the idea of a mini-module - Is it some magic in `go.mod` file or is it literally a different module ?

**Comment by DirectXMan12** [comment]
the idea is just to create a `tools` directory, and then have a separate go.mod file in that.  Take a look at what the CR makefile does: https://github.com/kubernetes-sigs/controller-runtime/blob/master/Makefile#L71
