### ISSUE TITLE
Role Bindings are not updated when the namespace marker is used

### ISSUE THREAD

**Issue by camilamacedo86** [kubernetes-sigs/controller-tools#513]
**What did you do?**
- Follow up the Kubebuilder quick start 
- Updated the controller as follows and then, run `make`

```go
// +kubebuilder:rbac:groups=webapp.my.domain,namespace=default,presources=guestbooks,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=webapp.my.domain,namespace=default,resources=guestbooks/status,verbs=get;update;patch
```

**What did you expect to see?**
All RBCA roles replaced to Namespace permissions.

**What did you see instead? Under which circumstances?**
Just the role.ymal was updated and note the role_binding.yaml. See: 
```

 $ cat role_binding.yaml 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: system

```

**NOTES:** 

I am as a user I'd like to be able to update all scaffolds files via marker or a helper to namespace scope as well and not just the role and role_binding which I understand, as described above, that should be done and has not been properly updated. 

- Bugfix: the controller-gen is not changing the role_binding. It is just changing the role. 

```
-rw-------   1 camilamacedo  staff  153  6 May 19:51 auth_proxy_client_clusterrole.yaml
-rw-------   1 camilamacedo  staff  280  6 May 19:51 auth_proxy_role.yaml
-rw-------   1 camilamacedo  staff  257  6 May 19:51 auth_proxy_role_binding.yaml
-rw-------   1 camilamacedo  staff  268  6 May 19:51 auth_proxy_service.yaml
-rw-------   1 camilamacedo  staff  419  6 May 19:51 leader_election_role.yaml
-rw-------   1 camilamacedo  staff  263  6 May 19:51 leader_election_role_binding.yaml
-rw-------   1 camilamacedo  staff  261  6 May 19:51 role_binding.yaml
```

**Environment**
- controller-gen 0.3.0

**Comment by prafull01** [comment]
Hi @camilamacedo86 

Currently, controller-tools only have the role markers and hence creates only roles in the RBAC. The scaffolding of rolebinding/clusterrolebinding is done on the kubebuilder side. You can see the scaffolding code [here](https://github.com/kubernetes-sigs/kubebuilder/blob/0149acd4bf33660e49e4e86dd9fcab10d5679236/pkg/plugin/v3/scaffolds/internal/templates/config/rbac/role_binding.go#L43)

Does the goal of this RFE is to create another marker which will create rolebinding/clusterrolebindings based on the  markers?
