### ISSUE TITLE
newline discrepancy in CRDs generated by controller-gen

### ISSUE THREAD

**Issue by marcoderama** [kubernetes-sigs/controller-tools#514]
Using controller-gen v0.4.0 (and older versions) for CRD generation on ubuntu, long descriptions are all on one line.  On a Mac, they're broken across multiple lines.  While both are equivalent from a YAML perspective, they're very different as far as git is concerned.  This means if dev A on ubuntu commits a CRD, and then dev B on MacOS makes a change that is effectively a small change to the yaml, the git diff is huge and completely obscures the actual change.  (And obviously the same happens if the order is dev B then dev A making changes.)

This makes it very difficult to review/understand CRD diffs and confuses devs.

Is there a way to make the outputs consistent?  If not, then I'd consider this a bug.

As an example, here's what happens for one of the descriptions in our CRD when going from generated-on-Mac to generated-on-ubuntu.  There is no diff yaml-wise but `git diff` includes:
```
           kind:
-            description: 'Kind is a string value representing the REST resource this
-              object represents. Servers may infer this from the endpoint the client
-              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
+            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
```

**Comment by marcoderama** [comment]
Fwiw, I tried

**Comment by derekperkins** [comment]
We have the same issues in v0.3.0

**Comment by marcoderama** [comment]
I guess we can just run the controller-gen output through a YAML pretty-printer before committing it.  It would seem reasonable to assume that's not necessary though.

**Comment by marcoderama** [comment]
This happens after running `make manifests`, as setup by kubebuilder.  I assumed it was due to `controller-gen` but it turns out the culprit is `kustomize`.
c.f. https://github.com/kubernetes-sigs/kustomize/issues/947

Sorry for casting aspersions your way.

(And working around it isn't a simple matter of piping things through `yq` (yet).  See https://github.com/mikefarah/yq/issues/573)

**Comment by zhangtbj** [comment]
Hi all,

I also found this problem on my Mac (without line-breaking), but my collea all generate WITH line-breaking.

I also tried on my Ubuntu VM, it also generates with line-breaking.

I don't know what happens on my Mac, I also upgrade my Golang to 1.15 or upgrade/downgrade controller-gen version, they all didn't work.

Do you have any other idea?

Thanks!

**Comment by PaulsBecks** [comment]
Hey all,

I too got this problem on my Mac, even though my colleagues do not. @zhangtbj did you find a solution?

Thanks

**Comment by zhangtbj** [comment]
Hi @PaulsBecks ,

I didn't fix it on my Mac, I switched to generate on my Ubuntu VM... :(

**Comment by zhangtbj** [comment]
Hi @PaulsBecks ,

I didn't fix it on my Mac, I switched to generate on my Ubuntu VM... :(

**Comment by imjasonh** [comment]
This seems to still be happening, without involving kustomize. On macOS YAML is generated with line wrapping, and on Ubuntu it's generated without line wrapping.

Does anybody have any ideas what might cause this discrepancy?

**Comment by akram** [comment]
This requires kubernetes-sigs/yaml to bump to version v2.4.0. Actually v2.3.0 would fix it, but it would introduce many regressions to kubernetes, so v2.4.0 reverted the fix but introduced the method `yaml.FutureLineWrap`  to disable line wrapping.
Once kubernetes-sigs/yaml  bumps a new version, controller-gen will need to call  `yaml.FutureLineWrap` to globally disable line wrapping.

**Comment by antonu17** [comment]
Confirm the issue on my macbook. Managed to mitigate like this:

1. update gopkg.in/yaml.v2 to the latest
2. rebuild controller-gen

Example:

```bash
go get gopkg.in/yaml.v2
go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.4.1
```
