### ISSUE TITLE
CRD validation for status when using status subresource

### ISSUE THREAD

**Issue by busser** [kubernetes-sigs/controller-tools#515]
How can I use CRD validation on my custom resource's status when I have the status subresource enabled? Is it even possible?

For example, let's say I define this API:

```go
type MySpec struct {}

type MyStatus struct {
    // +kubebuilder:default=Pending
    Phase string `json:"phase,omitempty"`
}

// +kubebuilder:object:root=true
type MyResource struct {
    metav1.TypeMeta   `json:",inline"`
    metav1.ObjectMeta `json:"metadata,omitempty"`

    Spec   MySpec   `json:"spec,omitempty"`
    Status MyStatus `json:"status,omitempty"`
}
```

When I create a new instance of `MyResource` in the Kubernetes API, the `.status.phase` field is set to `Pending` by default. Everything works as expected.

Now, let's say I enable the `status` subresource like this:

```go
type MySpec struct {}

type MyStatus struct {
    // +kubebuilder:default=Pending
    Phase string `json:"phase,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type MyResource struct {
    metav1.TypeMeta   `json:",inline"`
    metav1.ObjectMeta `json:"metadata,omitempty"`

    Spec   MySpec   `json:"spec,omitempty"`
    Status MyStatus `json:"status,omitempty"`
}
```

Even though the OpenAPI spec is updated in my CRD, Kubernetes does not perform defaulting or validation of any kind on fields in my resource's status.

If my understanding of the documentation is correct, this is to be expected:

> When enabled: 1. requests to the custom resource primary endpoint ignore
> changes to the `status` stanza of the object. 2. requests to the custom
> resource `/status` subresource ignore changes to anything other than the
> `status` stanza of the object.

I guess that this is also why any changes I make to the `.status` field in my resource's mutating webhook are ignored.

---

So is there a way to set default values for fields in the `status` stanza when the `status` subresource is enabled?

**Comment by sbueringer** [comment]
> So is there a way to set default values for fields in the status stanza when the status subresource is enabled?

What happens when you configure defaults + use the status endpoint to write the status?
