### ISSUE TITLE
Is it possible to install only controller-gen library?

### ISSUE THREAD

**Issue by LAnastasiia** [kubernetes-sigs/controller-tools#520]
Hi! Is it possible to use controller-gen CLI without using kubebuilder? 

If yes, how can I install it?
I couldn't find any installation guidelines for controller-gen exclusively. Is there one? (or really any pointer on how to do it would be appreciated)

More context:
Environment does not support kubebuilder integration yet, but does support controller-tools. 
From https://book.kubebuilder.io/reference/controller-gen.html#controller-gen-cli it looks like controller-gen covers the need of scaffolding for the project completely. But although I have kubebuilder installed, the controller-gen command can not be found. So I'm looking for a way to install it separately.

Thank you!

**Comment by estroz** [comment]
You can import things in `pkg/` to run generators. controller-gen's [`main.go`](https://github.com/kubernetes-sigs/controller-tools/blob/master/cmd/controller-gen/main.go) is a good (the best?) implementation to reference.

**Comment by prashao** [comment]
@LAnastasiia To install just the controller-gen binary you can do the following - 

1.  GOPATH env var should be set
2.  export GO111MODULE=on
3. go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.4.1

This will install controller-gen v0.4.1 binary in your GOPATH/bin directory.

**Comment by camilamacedo86** [comment]
@prashao and @LAnastasiia,
 
Btw kubebuilder also scaffolds the same install in the Makefile. See; https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3/Makefile#L81-L83

WDYT about we add the install instruction in the README? Would you like to push a PR for that?

**Comment by prashao** [comment]
@camilamacedo86 
Yeah I'll create a PR to update the README to install standalone controller-gen binary.

**Comment by prashao** [comment]
@camilamacedo86 
Have created PR https://github.com/kubernetes-sigs/controller-tools/pull/537
