### ISSUE TITLE
conflicting types in allOf branches in schema: string vs object

### ISSUE THREAD

**Issue by mjaow** [kubernetes-sigs/controller-tools#533]
When I'm trying to use the Conditions type from knative

```

import	"knative.dev/pkg/apis"

type MyStruct struct{
     Conditions apis.Conditions `json:"conditions,omitempty"
}

```
apis.Conditions  has a field with type VolatileTime 

```
type Condition struct{
      LastTransitionTime VolatileTime `json:"lastTransitionTime,omitempty" description:"last time the condition transit from one status to another"`
}

type VolatileTime struct {
	Inner metav1.Time `json:",inline"`
}
```

then I run `controller-gen crd:trivialVersions=true crd:crdVersions="v1beta1" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases`, 

it will faied with ` conflicting types in allOf branches in schema: string vs object`. 

From error message, I guess it's type error for VolatileTime, so I'm trying to figure a way to overrides the type for this field LastTransitionTime . But I can't do it as it's a field in knative

Does anyone know how to deal with it?

**Comment by mjaow** [comment]
I'm trying several versions , v0.4.0 works fine, but v0.4.1 failed with `conflicting types in allOf branches in schema: string vs object`

it seems after this PR https://github.com/kubernetes-sigs/controller-tools/pull/505 , it  doesn't work

**Comment by nitishkrishna** [comment]
I am getting the same exact error, my types.go has:
```
// Template wraps a json.RawMessage
// +kubebuilder:validation:Type=object
type TemplateSpec struct {
	json.RawMessage `json:",inline"`
}
```

**Comment by nitishkrishna** [comment]
I fixed my issue by moving to this release of controller-tools: `v0.4.1-0.20200821122629-1dc8cc4f84c8`

**Comment by mjaow** [comment]
look similar, but seems a different one. I think you fixed it due to v0.4.1-0.20200821122629-1dc8cc4f84c8 will generate an any type instead of object, any type has no conflict with string.  So it will work in v0.4.0 also at your scenerio

**Comment by markusthoemmes** [comment]
@mjaow this should now be fixed via the PR referenced above.

**Comment by aybansal-sudo** [comment]
i am facing a similar issue 
conflicting types in allOf branches in schema: string vs object
Error: not all generators ran successfully
my types.go file has
	// +kubebuilder:pruning:PreserveUnknownFields
	// +kubebuilder:validation:Type=object
	RequestPayload json.RawMessage `json:"requestPayload"`

after running controller-gen "crd:crdVersions={v1},trivialVersions=true" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
it failed with: conflicting types in allOf branches in schema: string vs object
Error: not all generators ran successfully. 
Any ideas on how to proceed with this?
