### ISSUE TITLE
Release with k8s 1.20 support?

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/controller-tools#545]
Thanks for the work on this tool. Is there a timeline when the next release with k8s 1.20 support will be released? I see that the dependencies has been updated in master. Is there any blocker for this release?

**Comment by tamalsaha** [comment]
cc; @vincepri

**Comment by vincepri** [comment]
@tamalsaha Just released v0.5.0, thanks for the reminder!

/close
