### ISSUE TITLE
[Question]: Generating CRDs for type that has field of type `map[something]interface{}`

### ISSUE THREAD

**Issue by viveksinghggits** [kubernetes-sigs/controller-tools#554]
I am using `kube-builder` that uses controller-tools to generate CRDs for the type definition for an already written project. If the types have a fields with type `map[string]interface{}` CRDs are not being generated successfully with error 
```
Error: not all generators ran successfully
```
take below type for an example 

```
type SomeType struct {
	Args       map[string]interface{}             `json:"args"`
}
```

I have similar situation in the case where the field type is `map[string]*SomeType`.
I was thinking if someone encountered this and has some pointers.

**Comment by leseb** [comment]
I've had a lot of troubles around this recently too and managed to get around it but the initial question from me would be, why do you need to use in `interface{} ` in the first place?

**Comment by viveksinghggits** [comment]
Hi @leseb, 
the problem is I am trying to create CRD for a project that we have already been maintaining using `v1beta1` version of CRDs. Do you think we should make changes in the code to have respective type for `interface{}`, or its worth creating CRD field for `interface{}`.

**Comment by leseb** [comment]
I guess it depends on how you are consuming the data, you could use `json.RawMessage`. But the AFAIK using `interface{}` has a type is not allowed/recommended by the API convention.

**Comment by viveksinghggits** [comment]
makes sense, thanks @leseb
