### ISSUE TITLE
Deprecating APIs support request 

### ISSUE THREAD

**Issue by tarvitz** [kubernetes-sigs/controller-tools#556]
In short,

Desired behavior: to have a possibility to deprecate API versions over markers

```go
// +kubebuilder:object:root=true
// +kubebuilder:resource:shortName=cf
// +kubebuilder:storageversion
// +kubebuilder:deprecated=true,message="use v1alpha2 resource instead"

// CloudFetchEntry is the Schema for the cloud fetch API objects
type CloudFetchEntry struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   CloudFetchEntrySpec `json:"spec,omitempty"`
	Status CloudFetchStatus    `json:"status,omitempty"`
}
```
Still, there's a workaround over a `schemapatch`, however, it makes a resource control procedure a bit more difficult (I leave a workaround unpublished until anyone requires it).

**Comment by erikgb** [comment]
This seems to have been fixed in https://github.com/kubernetes-sigs/controller-tools/pull/541.

/close
