### ISSUE TITLE
Rbac und CRD manifest file not generated

### ISSUE THREAD

**Issue by stevelaclasse** [kubernetes-sigs/controller-tools#581]
Hi everyone, 

i am writing an operator with Kubebuilder, everything works fine after the project creation but after i edited the types.go file and the controller.go file there are no generation of rbac or crd manifest files. the "make run" still work but the new variable i have added to my spec are not generated in crd yaml definition file and the kubebuilder markers i have added in the controller are not added in the role.yaml file.

> make generate

 and 

> make manifests

 are not showing any errors.

my environment is : 
- go : 1.16
- Kubebuilder : 3.1.0
- Kubernetes : 1.19.2
- controller-gen : 0.4.1 (sigs.k8s.io/controller-tools/cmd/controller-gen@v0.4.1)
- kustomize : 3.8.7  (sigs.k8s.io/kustomize/kustomize/v3@v3.8.7)

thanks for your help.

**Comment by yuswift** [comment]
cc
