### ISSUE TITLE
unable to recognize "STDIN": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"

### ISSUE THREAD

**Issue by gogogwwb** [kubernetes-sigs/controller-tools#582]
#make install
/opt/gopath/src/example/bin/controller-gen "crd:trivialVersions=true,preserveUnknownFields=false" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/opt/gopath/src/example/bin/kustomize build config/crd | kubectl apply -f -
error: unable to recognize "STDIN": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
make: *** [install] 错误 1

kubectl  1.15.3
kubebuilder  3.1.0

**Comment by yuswift** [comment]
`Kubernetes` v1.15 doesn't support apiextensions.k8s.io/v1. You need to upgrade your cluster version to v1.16 at least.
