### ISSUE TITLE
Generating CRD manifest for struct with recursive field

### ISSUE THREAD

**Issue by helpmeplsssss** [kubernetes-sigs/controller-tools#585]
My CRD spec looks like below:
```
type NodeSpec struct {
    Node `json:",inline"`
}

type Node struct {
    Children []Node `json:"children"`
    ...
}
```
Notice that the Node struct contains an array field that refers back to itself.

When I try to generate the CRD manifest for my spec (by running the make manifest command provided by Operator SDK -- it uses controller-gen v0.4.1), it produces this snippet:
```
children:
    items: {}
    type: array
```
When I try to apply the CRD manifest to my Kubernetes v1.19.7 cluster, I get this error:
```
The CustomResourceDefinition "node.example.com" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[children].items.type: Required value: must not be empty for specified array items
```
It's complaining that `children.items.type` is not defined.

How do I fix this?

**Comment by addreas** [comment]
Unless I'm missing something, it seems like the only way get Kubernetes to allow a recursive type in a CRD is to use `x-kubernetes-preserve-unknown-fields: true`. According to [the Kubernetes docs](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation) neither `$ref` nor `definitions` are allowed, which I guess means a "proper" solution to this would require changes outside of controller-tools.

Checking out the docs for the [validation markers](https://pkg.go.dev/sigs.k8s.io/controller-tools/pkg/crd/markers#XPreserveUnknownFields) it looks like `kubebuilder:pruning:PreserveUnknownFields` or the deprecated `kubebuilder:validation:XPreserveUnknownFields` should do the trick.

For example:
```
type NodeSpec struct {
    Node `json:",inline"`
}

type Node struct {
    // +kubebuilder:pruning:PreserveUnknownFields
    Children []Node `json:"children"`
    ...
}
```

**Comment by Skarlso** [comment]
Thank you @addreas. This saved my bacon. :)

**Comment by thoho** [comment]
@helpmeplsssss did you try the 
// +kubebuilder:pruning:PreserveUnknownFields
// +kubebuilder:validation:Schemaless
and got it to work?

**Comment by akutz** [comment]
Related to https://github.com/kubernetes/kubernetes/issues/62872
