### ISSUE TITLE
Support for Enum values for IntOrString type

### ISSUE THREAD

**Issue by prometherion** [kubernetes-sigs/controller-tools#591]
I got a CRD schema like the following.

```yaml
apiVersion: capsule.clastix.io/v1beta1
kind: Tenant
spec:
  namespaceQuota: 10
```

Following, the Go struct type.

```go
import (
	"k8s.io/apimachinery/pkg/util/intstr"
)

type TenantSpect struct {
  NamespaceQuota intstr.IntOrString `json:"namespaceQuota,omitempty"`
}
```

I'd like to provide a way to set a numeric value or some enum strings but I'm getting the following error:

`The Tenant "gas" is invalid: spec.namespaceQuota: Unsupported value: 3: supported values: "Unlimited"`

An actual workaround could be to go for the `string` type marked with `pattern`, although using it for integers doesn't look so good.

---

_Edit_: well, the error is on Kubernetes validation side, so not directly related to `controller-tools`. Maybe we could use the `pattern` here and make it appliable to `IntOrString` type and not only to `string`?

https://github.com/kubernetes-sigs/controller-tools/blob/ea8d4ead3e34dac7bb792cedc6d3cd7decf63137/pkg/crd/markers/validation.go#L300-L306

**Comment by JoelSpeed** [comment]
> Edit: well, the error is on Kubernetes validation side, so not directly related to controller-tools. Maybe we could use the pattern here and make it appliable to IntOrString type and not only to string?

I've just come across this part of this issue. While the pattern won't work if you input an integer, it's not invalid. The pattern still applies when giving a string argument to the to CR. This can be useful for example to limit the IntOrString to either an integer or a percentage value, eg with pattern `// +kubebuilder:validation:Pattern="^((100|[0-9]{1,2})%|[0-9]+)$"`

**Comment by alvaroaleman** [comment]
Pattern should be fixed with the latest change by @JoelSpeed ; feel free to re-open if you encounter more issues.
/close
