### ISSUE TITLE
go1.17: zz_generated.deepcopy.go changes when gofmt'd

### ISSUE THREAD

**Issue by benpbrown** [kubernetes-sigs/controller-tools#594]
The Go team has started the process of replacing the old "// +build" constraints with the new "//go:build" constraints. See the design doc for more details here:

https://go.googlesource.com/proposal/+/master/design/draft-gobuild.md

What is relevant is that in Go 1.17, gofmt now synchronizes the two styles. In particular, if gofmt is run against a deepcopy generated file, it will add a new "//go:build" constraint.

See https://golang.org/doc/go1.17#gofmt for details.

This issue to track making it so that zz_generated.deepcopy.go does not change when run under gofmt.

**Comment by erdii** [comment]
AFAIK controller-gen is already running gofmt internall here: https://github.com/kubernetes-sigs/controller-tools/blob/f8684f404f0f430181712b0f90721f90fb3637c6/pkg/deepcopy/gen.go#L260

**Comment by Porges** [comment]
Even before 1.17 this is an issue; `controller-gen` generates empty `import ()` blocks that disappear upon `fmt`ing.
