### ISSUE TITLE
install controller-gen failed: sf.IsExported undefined

### ISSUE THREAD

**Issue by ycyxuehan** [kubernetes-sigs/controller-tools#643]
```bash
go build -o ${HOME}/go/bin/controller-gen main.go
# sigs.k8s.io/json/internal/golang/encoding/json
/root/go/pkg/mod/sigs.k8s.io/json@v0.0.0-20211020170558-c049b76a60c6/internal/golang/encoding/json/encode.go:1249:12: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
/root/go/pkg/mod/sigs.k8s.io/json@v0.0.0-20211020170558-c049b76a60c6/internal/golang/encoding/json/encode.go:1255:18: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
go version
go version go1.16.10 linux/amd64
```

**Comment by Thor-wl** [comment]
+1

**Comment by HeGaoYuan** [comment]
+1

**Comment by Dimss** [comment]
+1

**Comment by sonujose** [comment]
Same issue
golang - 1.16.9

**Comment by Thor-wl** [comment]
I've solved this problem by upgating golang to v1.17

**Comment by HeGaoYuan** [comment]
Can it be solved by not upgating golang to v1.17

**Comment by Thor-wl** [comment]
> 

Unfortunately, I tried some ways but all failed.

**Comment by dineshputchala** [comment]
@Thor-wl Updating to 

> I've solved this problem by upgating golang to v1.17. Not sure whether it is a bug for v1.16 or not.

Updating to latest golang is solving this issue ?

**Comment by Thor-wl** [comment]
> 

Yes

**Comment by Thor-wl** [comment]
> @Thor-wl Updating to
> 
> > I've solved this problem by upgating golang to v1.17. Not sure whether it is a bug for v1.16 or not.
> 
> Updating to latest golang is solving this issue ?

Yes

**Comment by yuswift** [comment]
cc

**Comment by ngood97-splunk** [comment]
I believe this is related: https://github.com/kubernetes-sigs/json/issues/8

**Comment by Thor-wl** [comment]
> I believe this is related: [kubernetes-sigs/json#8](https://github.com/kubernetes-sigs/json/issues/8)

+1

**Comment by lmcdasm** [comment]
Same issue here, trying to bump golang version, but it causes massive refactor to lots of other components.

Any alternative options?

**Comment by ls-2018** [comment]
+1

**Comment by titaneric** [comment]
same here with Go version 1.16.5,

**Comment by moluzhui** [comment]
The same problem is in go1.16, which lower version can solve this problem? Thanks

**Comment by dineshputchala** [comment]
Not observed this issue in v1.17.8

**Comment by davidlanouette** [comment]
`reflect.StructField` was added in go 1.17.  If you are using it and compiling with an earlier version of go, you will have a bad time.

**Comment by dgloe-hpe** [comment]
The install guide says that go 1.16 is required, is that not the case any more?
https://sdk.operatorframework.io/docs/building-operators/golang/installation/

**Comment by camilamacedo86** [comment]
HI @dgloe-hpe, 

The SDK will use go get to check this one, see https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/Makefile#L150-L153 and inform the version.

So each SDK bin/release is compatible with which does.

The doc shared here is outdated because that should match with the latest release and the latest one uses go 1.17, see: https://github.com/operator-framework/operator-sdk/blob/v1.18.1/go.mod#L3

So, could you please raise an issue against the SDK repo asking for the doc be updated and have the info that the go version needs to be >= 1.17 < 1.18? Also, feel free to contribute with by pushing a PR. Your collab is very welcome.

**Comment by camilamacedo86** [comment]
Regards this issue, controller-tools is using go 1.17 and have it solved. See its latest release 0.8.0: https://github.com/kubernetes-sigs/controller-tools/blob/v0.8.0/go.mod#L3

So, I am closing this one. however, if anyone need help in the future regards this one then please feel free to raise a new issue.

**Comment by zhaowei413** [comment]
the same issue with you on go 1.16. Fixed after upgrade to go1.18.....
