### ISSUE TITLE
Feature Request: support array type for printcolumn

### ISSUE THREAD

**Issue by damnever** [kubernetes-sigs/controller-tools#652]
It only show the first item of the array. Maybe we should support array type with custom separator, the default separator could be comma, e.g. "a,b,c".

**Comment by damnever** [comment]
ping

**Comment by damnever** [comment]
🔢 
/remove-lifecycle stale

**Comment by FillZpp** [comment]
Unfortunately, the [OpenAPI data-types](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#data-types) which is used by CRD to define its additionalPrinterColumns does not support array type.

**Comment by FillZpp** [comment]
@damnever That's different. The columns of those built-in resources are defined in kubectl logic, which can easily print any data they want. But CRD, on the other hand, can only define columns in `additionalPrinterColumns` with OpenAPI data-types.

**Comment by adyanth** [comment]
Sad to see this is not supported. Is there a way to generate the string to show? Or since this is all client side, nothing much can be done?
