### ISSUE TITLE
Add support for adding annotations to CRD

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes-sigs/controller-tools#656]
For kubernetes projects, if we want to use the `sig.k8s.io` group for CRDs, we need to provide the annotation `api-approved.kubernetes.io`. Otherwise, apiserver rejects the CRD.

As a result, we have to manually edit the CRDs produced by `controller-gen` and continuously edit the files every time there is a type update.

Using kustomize is not possible, because the env-test doesn't load them and it could be problematic to do so (it's an additional dependency).

/kind feature

**Comment by helayoty** [comment]
This feature is really needed. Any way to help implementing it?
