### ISSUE TITLE
Unable to make multiple webhook-enabled controller deployments

### ISSUE THREAD

**Issue by muvaf** [kubernetes-sigs/controller-tools#658]
In Crossplane, we have a single webhook server for core Crossplane controllers and an arbitrary number of webhooks deployed by the provider controllers. All of those are usual controller-runtime controllers and webhooks.

However, the generated `ValidatingWebhookConfiguration` and `MutatingWebhookConfiguration` files have [static hard-coded names](https://github.com/kubernetes-sigs/controller-tools/blob/0fba82b/pkg/webhook/parser.go#L367), which means that when we install one or more providers, they override the original configuration that was installed for Crossplane itself. So, the providers and Crossplane fight over a single object.

We could either add a new field to the `webhook` marker or derive the name from somewhere smart enough that it will differentiate one another.

I'd be willing to contribute the change if we can come to a solution/workaround.

**Comment by negz** [comment]
@muvaf Does this mean that it's actually not possible to install two controller managers that a) are built with kubebuiler/controller-tools, and b) use webhooks? That does seem like a problem.

**Comment by muvaf** [comment]
@negz That's what I can tell. There might be some point during the deployment of the controller where the names of these resources are patched but I couldn't find it. [This](https://github.com/kubernetes-sigs/kubebuilder/tree/master/docs/book/src/cronjob-tutorial/testdata/project/config/webhook) is an example project referenced from the kubebuilder book.

**Comment by FillZpp** [comment]
> However, the generated ValidatingWebhookConfiguration and MutatingWebhookConfiguration files have [static hard-coded names](https://github.com/kubernetes-sigs/controller-tools/blob/0fba82b/pkg/webhook/parser.go#L367), which means that when we install one or more providers, they override the original configuration that was installed for Crossplane itself. So, the providers and Crossplane fight over a single object.

@muvaf  Not at all. Take [this sample project in Kubebuilder](https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3-config) as an example:

Although the ValidatingWebhookConfiguration and MutatingWebhookConfiguration YAMLs generated by controller-tools have names `mutating-webhook-configuration` and `validating-webhook-configuration` ([see](https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3-config/config/webhook/manifests.yaml)), but it has kustomize `namePrefix` which should be the project name ([see](https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v3-config/config/default/kustomization.yaml#L9)).

So when you `make deploy`, which actually executes `$(KUSTOMIZE) build config/default | kubectl apply -f -`, kustomize will generate names of the real webhook YAMLs as `<project-name>-mutating-webhook-configuration` and `<project-name>-validating-webhook-configuration`.

Unless you have two different services of webhook configurations in a same project scaffolded by Kubebuilder, that is not supported by controller-tools.
