### ISSUE TITLE
Unclear on k8s.io/code-generator utils vs controller-gen tool

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/controller-tools#661]
I am a newcomer to the ecosystem and I cannot tell when to use

https://github.com/kubernetes/code-generator/blob/master/generate-groups.sh,
https://github.com/kubernetes/code-generator/blob/master/hack/update-codegen.sh or
https://github.com/kubernetes-sigs/controller-tools/tree/master/cmd/controller-gen

For example `controller-gen` can do deepcopy generation, and so can https://github.com/kubernetes/code-generator/tree/master/cmd/deepcopy-gen.

Similarly, `controller-gen` can do OpenAPI v3 schema generation, and so can https://github.com/kubernetes/code-generator/blob/master/cmd/openapi-gen/main.go

Is `controller-gen` a one-stop shop? 

I hope this piece of feedback is somewhat useful.

**Comment by Porges** [comment]
Note that the usual entrypoint is to use the overarching [Kubebuilder project](https://book.kubebuilder.io/) which uses `controller-gen` “under the hood”, and when doing this you do not need to call `controller-gen` directly as the provided `Makefile` takes care of this for you.

However, if you want to use `controller-gen` by itself then yes, it can be used as a one-stop shop, without any other of the tools you mentioned. I haven’t used anything from the `code-generator` project myself, so cannot comment on that.
