### ISSUE TITLE
Proposing `v0.9.1` Release

### ISSUE THREAD

**Issue by brycahta** [kubernetes-sigs/controller-tools#667]
Opening this issue per the [Release Process](https://github.com/kubernetes-sigs/controller-tools/blob/master/RELEASE.md) to cut a new release of `controller-tools`. The latest release was cut _Jan-5_, the change log since then is as follows:

https://github.com/kubernetes-sigs/controller-tools/compare/v0.8.0...master

![image](https://user-images.githubusercontent.com/61433408/166487461-5d321c71-7d64-447e-a4c5-8b7313e384df.png)

**Comment by Porges** [comment]
@brycahta I am not in the `OWNERS` file… pinging @alvaroaleman & @joelanford

**Comment by rahulanand16nov** [comment]
Yes, waiting for the changes to be present in the new release :pray:

**Comment by joelanford** [comment]
Hey folks -- this is on the todo list. This week is KubeCon EU, so the maintainers here are pretty busy. I'd expect that we'll be able to circle back and cut a new release by the end of May.

**Comment by alvaroaleman** [comment]
We need some kind of fix for https://github.com/kubernetes-sigs/controller-tools/issues/680 before we do a release

**Comment by joelanford** [comment]
v0.9.0 was released last week. I'll rename this to cover the 0.9.1 release we'll need.

**Comment by brycahta** [comment]
>  ...and cut a new release by the end of May.

@joelanford , assuming this was referring to `v0.9.0` is there an ETA for `v0.9.1` release? Looks like https://github.com/kubernetes-sigs/controller-tools/issues/680 was fixed.

**Comment by brycahta** [comment]
Released: https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.9.1
