### ISSUE TITLE
Generating CRD in go code

### ISSUE THREAD

**Issue by Pixcell** [kubernetes-sigs/controller-tools#668]
Hello :)

Thank you for the amazing work you guys are doing!

I have been using `make manifests` to generate my CRDs, and everything works perfectly fine.

However, I now need to generate the `CustomResourceDefinition` object directly in golang code, based on the struct I have defined and annotated in my `_types.go` file. Because I manages my cluster from go code using the k8s APIs and not using yaml files.

From browsing the code in this repo, I feel like the solution is there somewhere in the `pkg/crd` folder. However, this is a lot of code to browse through (Thanks again for the hard work).

Would you happen to have any doc on how to generate CRD inside go code, and not as a YAML file?

Any help is greatly appreciated! 
Thank you

**Comment by Pixcell** [comment]
Current workaround:
```

		versions[idx].Schema = &extsv1.CustomResourceValidation{
			OpenAPIV3Schema: &extsv1.JSONSchemaProps{
				Properties: map[string]extsv1.JSONSchemaProps{},
				XPreserveUnknownFields: &preserveUnknownFields,
				Type:                   "object",
			},
		}
```

Which will generate a valid schema that does not do any validation. Which is not good enough for production environments

**Comment by Porges** [comment]
The struct that is in the `_types.go` file can be used to communicate with the cluster from Go code without using YAML files.

For example, if you have a [`Client`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/client#Client) (from `controller-runtime`)  you can invoke [`client.Create(ctx, myStruct)`](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/client#Writer) to create a resource in the cluster.

**Comment by Pixcell** [comment]
Hi @Porges,

Thanks for the response, but I fear I might not have explained my problem properly.
My problem is not interacting with the CRs in the cluster, but how to, using go code create the CRDs in the cluster.

When I tried to create a CRDs using go code, it complains about OpenAPIV3Schema being required. And to be honest, I don't want to write this struct manually (because I am lazy, and because it will be a pain to keep it up-to-date with the struct), when I am almost your controller-gen code can generate it from reading the struct files. (Because from what I gathered reading `pkg/crd` code, that's what you guys are doing in controller-gen)

Thank you

**Comment by yuvDev-hub** [comment]
what's the status on this one?

**Comment by carreter** [comment]
In case anyone stumbles across this:

I was facing a similar issue on a project, ended up finding that `sigs.k8s.io/controller-runtime/pkg/envtest` has a handy-dandy `InstallCRDs()` function that reads CRD manifests from disk and creates them in the apiserver. This opens the door for a very hacky workaround that uses `controller-gen` to generate the types and CRD YAML files.

I'd still be interested in seeing code generation handle this, though! I have 0 experience with code generation and am slammed at work, but I may take a look :)
