### ISSUE TITLE
Install prerequisites are incomplete

### ISSUE THREAD

**Issue by BarthV** [kubernetes-sigs/controller-tools#670]
![image](https://user-images.githubusercontent.com/1901955/166665292-9473b33f-3d5c-416a-b6a9-cf5ce2fabbff.png)

You also need to add controller-gen in this list.
+ the current install fails when using controller-gen >= 0.7.0

It only works with 0.6.2 ATM

**Comment by Porges** [comment]
Hi @BarthV, it seems like this is an issue with [the k6 documentation](https://k6.io/blog/running-distributed-tests-on-k8s/)?
