### ISSUE TITLE
controller-gen: Deterministic ordering for CRD output manifests (output:stdout)

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/controller-tools#675]
Every time I run `controller-gen` to generate YAML manifest for my CRDs, I get a different output.

Often, the `CustomResourceDefinition` objects that it spits out and separates with `---` in yaml doc are in different orders. For example if I have CRDs named Type1, Type2, Type3, the order in which they appear in YAML keeps shuffling.

This makes it hard/impossible to write validation/tests that ensure the version-controlled generated artifact (my `crds.yaml`) is up-to-date with what would be generated (hence, prevent drifts + ensure commit consistency).

For posterity, I'm running:

```
go run sigs.k8s.io/controller-tools/cmd/controller-gen@v0.8.0 \
                crd:maxDescLen=0,generateEmbeddedObjectMeta=true \
                paths=./pkg/apis/... output:stdout > ./deployment/crds.yaml
```

I have 5 CRDs so I have 120 permutations, if I run the cmd ~100 times, I definitely see some identical checksums of the output, so I think we just need to order the CRDs by name in the output.

**Comment by ahmetb** [comment]
Looking at `OutputToStdout` writer I can't really tell what causes this non-determinism. https://sourcegraph.com/github.com/kubernetes-sigs/controller-tools@a260f1391b0f722e07ae04fe87e23e32bc1a1ec7/-/blob/pkg/genall/output.go?L85 So I think the order in which the parsing/collecting is done might not be deterministic.

**Comment by Porges** [comment]
It will be due to the use of `map` somewhere. Order is randomized upon every run.

**Comment by ahmetb** [comment]
Yep, it seems to be here https://sourcegraph.com/github.com/kubernetes-sigs/controller-tools@a260f1391b0f722e07ae04fe87e23e32bc1a1ec7/-/blob/pkg/crd/gen.go?L118-122
