### ISSUE TITLE
openAPIV3Schema generated by controller-gen for map doesn't have allows: true in additionalProperties

### ISSUE THREAD

**Issue by yongxiu** [kubernetes-sigs/controller-tools#714]
In https://github.com/kubernetes/kubernetes/issues/104137#issuecomment-1215575261, I just learnt that if you want to allow arbitrary key in maps, you need to specify allows: true in additionalProperties for a map.

However for a normal map, controller-gen will not add this `allows: true` in the additionalProperties, causing adding key and value failed the schema validation

kuebuilder example:
```
// +kubebuilder:validation:Optional
Labels map[string]string `json:"labels,omitempty"`
```

Generated CRD's openAPIV3Schema
```
labels:
   additionalProperties:
       type: string
```

When validating this openAPIV3Schema against a normal yaml:
```
labels:
    "key1": "value1"
```

It will give errors
```
* [].spec.labels: Invalid value: "key1": spec.labels.key1 in body is a forbidden property
```

**Comment by liggitt** [comment]
> you need to specify allows: true in additionalProperties for a map.

the `Allows: true` is not required in the yaml `additionalProperties` openAPIV3Schema, it's required when constructing an in-memory `AdditionalProperties: &apiextensions.JSONSchemaPropsOrBool{...}`

the openAPIV3Schema generated here looks correct

**Comment by yongxiu** [comment]
But if I use the generated openAPIV3Schema to validate above YAML file, it will give errors:
```
[].spec.labels: Invalid value: "key1": spec.labels.key1 in body is a forbidden property
```

---
The function I used is 
```
import (
	apiservervalidation "k8s.io/apiextensions-apiserver/pkg/apiserver/validation"
)

apiservervalidation.ValidateCustomResource(field.NewPath(""), nodePool, nodePoolSchemaValidator)
```

nodePoolSchemaValidator is loaded using 
```
var version *apiextensions.CustomResourceDefinitionVersion
for i, v := range crd.Spec.Versions {
if v.Storage {
	if version == nil {
		version = &crd.Spec.Versions[i]
	} else {
		return nil, fmt.Errorf("there must be exactly one flagged as storage version for CustomResourceDefinition %s, but found multiple: %v, %v", crd.Name, version, crd.Spec.Versions[i])
	}
}
}
if version == nil {
return nil, fmt.Errorf("no version found for CustomResourceDefinition: %s", crd.Name)
}
schema := version.Schema
if schema == nil {
return nil, fmt.Errorf("there must be non-nil schema in CustomResourceDefinitionVersion in the CRD YAML file %s, but found a nil schema", yamlFilePath)
}
schemaValidator, _, err := apiservervalidation.NewSchemaValidator(schema)
if err != nil {
return nil, fmt.Errorf("failed to create new schema validator for for schema %+v: %w", schema, err)
}
```

**Comment by yongxiu** [comment]
Btw, if I manually add `allows: true` in the openAPIV3Schema yaml file, it will not give errors any more.

So it's either `controller-gen`'s bug or https://github.com/kubernetes/kubernetes/issues/104137 ?

**Comment by liggitt** [comment]
how are you constructing the `crd` instance in your example?

**Comment by yongxiu** [comment]
```
b, err := ioutil.ReadFile("..../base/crd/bases/nodepools.yaml")
if err != nil {
return nil, fmt.Errorf("failed to get CRD file %s: %w", yamlFilePath, err)
}
crd := &apiextensions.CustomResourceDefinition{}
if err := yaml.Unmarshal(b, crd); err != nil {
return nil, fmt.Errorf("failed to unmarshal CRD file %s: %w", yamlFilePath, err)
}
```

`..../base/crd/bases/nodepools.yaml` is generated by controller-gen

**Comment by liggitt** [comment]
`yaml.Unmarshal` won't work directly like that... that is bypassing the customized JSON unmarshaling implementation in `JSONSchemaPropsOrBool#UnmarshalJSON` that sets `Allow` to `true` internally

You'll need to either convert the yaml to json and unmarshal json into the struct, or use the apimachinery yaml unmarshaler (which does the same thing)

**Comment by yongxiu** [comment]
You mean like below
```
import (
	utilyaml "k8s.io/apimachinery/pkg/util/yaml"
)

crd := &apiextensions.CustomResourceDefinition{}
if err := utilyaml.Unmarshal(b, crd); err != nil {
return nil, fmt.Errorf("failed to unmarshal CRD file %s: %w", yamlFilePath, err)
}
var version *apiextensions.CustomResourceDefinitionVersion
for i, v := range crd.Spec.Versions {
if v.Storage {
	if version == nil {
		version = &crd.Spec.Versions[i]
	} else {
		return nil, fmt.Errorf("there must be exactly one flagged as storage version for CustomResourceDefinition %s, but found multiple: %v, %v", crd.Name, version, crd.Spec.Versions[i])
	}
}
}
if version == nil {
	return nil, fmt.Errorf("no version found for CustomResourceDefinition: %s", crd.Name)
}
```

The result is same..

**Comment by liggitt** [comment]
That's still using direct yaml → struct deserialization, which won't work.

You'd need to either convert yaml to json using sigs.k8s.io/yaml#YAMLToJSON and then do `json.Unmarshal(jsonData, &crd)`, or use the apimachinery yaml deserializer (k8s.io/apimachinery/pkg/runtime/serializer/json#NewYAMLSerializer), which just does the same thing under the covers.

**Comment by liggitt** [comment]
It also looks as though you might be trying to decode serialized yaml data into unversioned types... are you using `k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1#CustomResourceDefinition` or `k8s.io/apiextensions-apiserver/pkg/apis/apiextensions#CustomResourceDefinition`? For decoding yaml or json data to work correctly, you have to use the versioned type in the v1 package.

**Comment by yongxiu** [comment]
Thanks Jordan, yes, NewYAMLSerializer works!

And I do need to use v1 version of CustomResourceDefinition.
