### ISSUE TITLE
Lint check fails in groupversion_info.go

### ISSUE THREAD

**Issue by nikfot** [kubernetes-sigs/controller-tools#716]
### What broke? What's expected?

Some comments in the groupversion_info.go file do not end in "."(dot) causing golangci-lint checks to fail. It is minor but I am letting it here.
```
	// GroupVersion is group version used to register these objects
	GroupVersion = schema.GroupVersion{Group: "grow.upstreamsystems.com", Version: "v1alpha1"}

	// SchemeBuilder is used to add go types to the GroupVersionKind scheme
	SchemeBuilder = &scheme.Builder{GroupVersion: GroupVersion}
```
_The same happens for the spec comment of the created api._
### Reproducing this issue

It can be re produced by using the simple commands of `kubebuilder init` and `kubebuilder create api`

### KubeBuilder (CLI) Version

Version: main.version{KubeBuilderVersion:"v3.5.0", KubernetesVendor:"unknown", GitCommit:"26d12ab1134964dbbc3f68877ebe9cf6314e926a", BuildDate:"2022-08-23T12:55:30Z", GoOs:"linux", GoArch:"amd64"}

### PROJECT version

3

_I copied it from [this](https://github.com/kubernetes-sigs/kubebuilder/issues/2893), i could issue a PR if it's ok_

**Comment by camilamacedo86** [comment]
Hi @nikfot,

Could you please let us know if the problem still?
If so could you please share the version of controller-gen used and confirm that it still faced with the latest?

**Comment by nikfot** [comment]
Hello @camilamacedo86 ,
It is the group, however I am not sure how this has to do with the problem, since the problem was a minor one concerning linting.

Linting fails because the comments do not have a dot at the end. I have added a dot myself as in:
```
// GroupVersion is group version used to register these objects.
