### ISSUE TITLE
DeepCopy file was not generated

### ISSUE THREAD

**Issue by tomer-epstein** [kubernetes-sigs/controller-tools#721]
`version: v0.9.0`
`os: windows`

`command:  controller-gen object:headerFile="hack\\boilerplate.go.txt" paths="./..."`

downgrading to v0.8.0 or v0.7.0 fixes the issue.

**same issue also for generating role and webhook**
`controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=csigs.k8s.io/controller-tools/cmd/controller-gen@v0.9.0cts:config=config/crd/bases`

**Comment by camilamacedo86** [comment]
This one is an old version and you are using windows which is not officially supported by the tool.
In this way, I think we can close this one and re-open it if you are able to face the same problem using linux or mac and with the latest release. Please, feel free to re-open if that be the case.
