### ISSUE TITLE
Hide `// TODO:` from generated CRD.

### ISSUE THREAD

**Issue by kaovilai** [kubernetes-sigs/controller-tools#728]
Would be awesome to be able to annotate each `_types.go` field if there is a TODO but without having it live in a CRD for end users to see.

**Comment by cbandy** [comment]
Related: #649

**Comment by camilamacedo86** [comment]
Hi @kaovilai,

Would you like to work on a PR to propose this solution?

**Comment by kaovilai** [comment]
I'm open to it :)

**Comment by kaovilai** [comment]
unstale

**Comment by sbueringer** [comment]
/ifecycle frozen

I think it makes sense to strip TODO's like upstream. We don't want TODOs showing up in CRDs, espeically if they are on types from k/k.

**Comment by mythi** [comment]
seems to be fixed in 0.16.x?

**Comment by sbueringer** [comment]
Yeah, I think so! 

I didn't remember this issue exists :)

/close
