### ISSUE TITLE
Generate groupversion_info.go similar to register.go

### ISSUE THREAD

**Issue by adammw** [kubernetes-sigs/controller-tools#729]
Feature Request:

Generate groupversion_info.go similar to [kubernetes/code-generator](https://github.com/kubernetes/code-generator) [register.go](https://github.com/kubernetes/sample-controller/blob/master/pkg/apis/samplecontroller/v1alpha1/register.go)

A sample groupversion_info.go contains:
```
var (
	// GroupVersion is group version used to register these objects
	GroupVersion = schema.GroupVersion{Group: "example.com", Version: "v1alpha1"}

	// SchemeBuilder is used to add go types to the GroupVersionKind scheme
	SchemeBuilder = &scheme.Builder{GroupVersion: GroupVersion}

	// AddToScheme adds the types in this group-version to the given scheme.
	AddToScheme = SchemeBuilder.AddToScheme
)
```

Kubernetes-style API types instead use the variable name `SchemeGroupVersion`, and contain the additional helper methods:
```
// Kind takes an unqualified kind and returns back a Group qualified GroupKind
func Kind(kind string) schema.GroupKind {
	return SchemeGroupVersion.WithKind(kind).GroupKind()
}

// Resource takes an unqualified resource and returns a Group qualified GroupResource
func Resource(resource string) schema.GroupResource {
	return SchemeGroupVersion.WithResource(resource).GroupResource()
}
```

Ideally there should be consistency and feature-compatibility between the two code generators.

**Comment by camilamacedo86** [comment]
Hi @adammw,

This one is generated by Kubebuilder when you create the project within, see i.e.: https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v4-with-deploy-image/api/v1alpha1/groupversion_info.go

Therefore, could you please let us know why do think that it should be in the controller-gen? What is the motivation? What is the use case?

Also, if you wish please feel free to push a pull request with your proposal. However, we would also need to change Kubebuilder after the bump to no longer generate this one.
