### ISSUE TITLE
controller-gen DeepCopy tests?

### ISSUE THREAD

**Issue by NateThornton** [kubernetes-sigs/controller-tools#733]
Would there be any interest in generating a companion zz_generated.deepcopy_test.go file that contains some trivial validation logic so running go test with code coverage would be complete?

I'm not even sure it would need test assertions, just something simple

```go
package x

// Object X
// +kubebuilder:object:generate=true
type X struct {}
```

```go
package x

import "testing"

func TestXDeepCopyInto(t *testing.T) {
	in, out := X{}, X{}
	in.DeepCopyInto(&out)
}

func TestXDeepCopy(t *testing.T) {
	in := &X{}
	in.DeepCopy()
	in = nil
	in.DeepCopy()
}
```

I find in using kubebuilder after adding webhook and webhook suite test to our api/v1alpha1 folder, code coverage is abysmal, and having the generated code be covered would give an indication as to the lack of code coverage in the webhooks themselves.

**Comment by camilamacedo86** [comment]
This code is generated by the tool, so you would not need to cover with tests. I think your scenario is the same described in this issue: https://github.com/kubernetes-sigs/kubebuilder/issues/2645. Please, see the comment: https://github.com/kubernetes-sigs/kubebuilder/issues/2645#issuecomment-1126670250

In this way, I am closing this one as sorted out but if you see that should be re-opened please feel free to do so.
