### ISSUE TITLE
Release of supporting annotations to CRD fix

### ISSUE THREAD

**Issue by AaronPhilly** [kubernetes-sigs/controller-tools#751]
Hi all,
With regards to Issue #656 - I can see that the fix for this was merged last month. But from the look of releases there hasnt been a release which is usable that would have this functionality added. (Last release is from Sept 21st)

I have two questions here:
1) Can you give me any indication as to when we can expect a new release which will include the fix for #656 ?
2) Is there a way the code for the fix can be checked out and used without the official release?

/kind feature

**Comment by alvaroaleman** [comment]
v0.11 has been releases, which includes this.
