### ISSUE TITLE
x-kubernetes-map-type: Invalid value "null"

### ISSUE THREAD

**Issue by sxd** [kubernetes-sigs/controller-tools#757]
While upgrade to the new versions of controller-tools and controller-runtime in [CloudNativePG](https://github.com/cloudnative-pg/cloudnative-pg/issues/1237) we hit this error while deploying the generated CRD into KinD 1.26.0:

`
CustomResourceDefinition.apiextensions.k8s.io "clusters.postgresql.cnpg.io" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[walStorage].properties[pvcTemplate].properties[resources].properties[claims].items.x-kubernetes-map-type: Invalid value: "null": must be atomic as item of a list with x-kubernetes-list-type=set, spec.validation.openAPIV3Schema.properties[spec].properties[storage].properties[pvcTemplate].properties[resources].properties[claims].items.x-kubernetes-map-type: Invalid value: "null": must be atomic as item of a list with x-kubernetes-list-type=set, spec.validation.openAPIV3Schema.properties[spec].properties[resources].properties[claims].items.x-kubernetes-map-type: Invalid value: "null": must be atomic as item of a list with x-kubernetes-list-type=set]
`

We also hit the previous error #752 but this doesn't looks like it will match that error in specific and the patch doesn't seem to handled a `null` value at all 

Regards,

**Comment by sxd** [comment]
This was a bug using version 0.9.2, with version 0.11.0 works but with version 0.11.1 which has only the revert of #752

**Comment by JoelSpeed** [comment]
Your API type includes the `corev1.ResourceRequirements` struct which is currently broken in the K8s 1.26.0 release. The PR to fix it is https://github.com/kubernetes/kubernetes/pull/114617 and that will be included in v1.26.1, whenever that is being cut.

**Comment by sxd** [comment]
@JoelSpeed thank for your answer! I'll close this ticket then doesn't make sense at all, thanks for your reply!
