### ISSUE TITLE
Support metadata.name or subobject validation

### ISSUE THREAD

**Issue by bprashanth** [kubernetes-sigs/controller-tools#761]
I'd like to validate objectmeta fields like metadata.name. 
I can't find a way to do so currently. 
This would be very useful when used with https://github.com/kubernetes-sigs/kubebuilder/issues/1074

**Comment by JoelSpeed** [comment]
Have you looked at adding validation using CEL validation rules? https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation-rules

You might be able to achieve what you want with some rules on your top level object
