### ISSUE TITLE
Is there a way to generate Controller from existing CRD Yaml Spec?

### ISSUE THREAD

**Issue by RameshRM** [kubernetes-sigs/controller-tools#777]
Is there a way to generate Controller from existing CRD Yaml Spec?

I have a CRD Spec, is there  a way to generate the controller and CRD Definitions from the YAML rather than maintaining two versions one in Yaml and another in Go ?

**Comment by sbueringer** [comment]
No. We don't have anything coming close to generating controllers in controller-gen


/close
