### ISSUE TITLE
Generating OpenAPI spec (OAS) along with CRD

### ISSUE THREAD

**Issue by SantoshKumar4** [kubernetes-sigs/controller-tools#808]
Looking for suggestions.  
I am generating Kubernetes CRD (Custom Resource Definition) using kubebuilder. Along with CRD, I also need **to document** the REST endpoints by creating **OpenAPI v3 Spec (OAS)** file. Is there a way to get this done using controller-gen? (I see that kubebuilder uses controller-gen to create the CRD) and it was recommended to ask the question in this space). I tried exploring +schemapatch generator but felt like it's there for a different reason.

I also want to add sample Request/Response payload and other OpenAPI details (in <>types.go file) to generate complete OAS file.
The reason I want to use types.go file as I will have just one source of truth and I don't need to manually write/edit the OAS file.

Any other way would you recommend if controller-gen is not the right tool for this.

Thanks in advance.

**Comment by EronWright** [comment]
Related: https://github.com/kubernetes-sigs/kubebuilder/issues/1231

**Comment by camilamacedo86** [comment]
Also, see the markers for validation: https://book.kubebuilder.io/reference/markers/crd-validation

**Comment by caozhuozi** [comment]
> Also, see the markers for validation: https://book.kubebuilder.io/reference/markers/crd-validation

validation might not be the only purpose for OpenAPI Spec. We need the OpenAPI Spec for generating client codes in other languages.
