### ISSUE TITLE
controller-ger error

### ISSUE THREAD

**Issue by sam-germany** [kubernetes-sigs/controller-tools#811]
![56r](https://user-images.githubusercontent.com/66065583/236758299-fa52aa8b-d247-48b2-a543-894965630655.png)

i am trying to execute  "make install"  or "make docker-build"  both time i am getting this error, can you please help

**Comment by kkkkun** [comment]
You should install `controller-gen` firstly by `go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.12.0`

**Comment by 892195580** [comment]
> You should install `controller-gen` firstly by `go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.12.0`

![image](https://github.com/kubernetes-sigs/controller-tools/assets/37182663/f3a8ec4f-8d0f-41f7-9bfa-5e9f6322d816)
How could I solve this problem in this pic when I install controller-gen?

**Comment by sbueringer** [comment]
Looks like you're go version is not compatible. In Cluster API we use Go 1.20 with controller-gen v0.12
