### ISSUE TITLE
Should metav1.Time CRD generation specify nullable if the field is optional?

### ISSUE THREAD

**Issue by vsliouniaev** [kubernetes-sigs/controller-tools#812]
1. Create a CRD with a time field. For example ReleaseTime *metav1.Time `json:"releaseTime,omitempty`
2. The spec which gets generated doesn’t have releaseTime in the required section, which is as expected
3. Using `k8s.io/code-generator v0.27.1` generate a client.
4. Use the Apply method to try patch the resource, clearing the releaseTime field.
5. The [MarshalJson](https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/time.go#L141-L152) for time specifies that zero-value time will get marshalled to null
6. When the apply call is made to api the request is rejected with `spec.releaseTime: Invalid value: "null": spec.releaseTime in body must be of type string: "null"`
7. The solution to this appears to be to add the extra `//+nullable` marker to the field to get the schema to become
```
spec:
  properties:
    releaseTime:
      format: date-time
      nullable: true
      type: string
```      

Seems like this should happen by default if the field is optional.

**Comment by vsliouniaev** [comment]
remove-lifecycle rotten

**Comment by sbueringer** [comment]
Not sure if we want to start inferring additional markers based on types.

**Comment by vsliouniaev** [comment]
That's fair - thanks for the info. Feel free to close this if you feel like the behaviour is intentional.

**Comment by sbueringer** [comment]
Really not sure :), let's see if others have opinions.

(cc @vincepri @alvaroaleman )
