### ISSUE TITLE
Err when use controller-gen in chaos-mesh

### ISSUE THREAD

**Issue by 892195580** [kubernetes-sigs/controller-tools#831]
controller-gen crd:trivialVersions=true,preserveUnknownFields=false,crdVersions=v1 rbac:roleName=manager-role paths="./..." output:crd:artifacts:config=../config/crd/bases ;\
		controller-gen crd:trivialVersions=true,preserveUnknownFields=false,crdVersions=v1 rbac:roleName=manager-role paths="./..." output:crd:artifacts:config=../helm/chaos-mesh/crds ;

![image](https://github.com/kubernetes-sigs/controller-tools/assets/37182663/a1063d57-46a5-4a9b-9fac-728f9f6ec8b9)

if use make generate in root path of chaos-mesh,this happened:
![image](https://github.com/kubernetes-sigs/controller-tools/assets/37182663/7799cdfa-6764-4ace-8d71-ba03168af663)

**Comment by sbueringer** [comment]
Hard to tell what is going on based on the screenshot but looks like you have networking issues when downloading dependencies

**Comment by 892195580** [comment]
> Hard to tell what is going on based on the screenshot but looks like you have networking issues when downloading dependencies

yes，when run to "controller-gen" commands in a makefile, that will happen, but I have changed GOPROXY as "https://proxy.golang.cn".

**Comment by 892195580** [comment]
> Hard to tell what is going on based on the screenshot but looks like you have networking issues when downloading dependencies
I remove some conditions in the controller-gen which is trivialVersions=true,preserveUnknownFields=false,and I got new problem:
![image](https://github.com/kubernetes-sigs/controller-tools/assets/37182663/55bf19f0-738d-4365-9692-2295d58e6133)
