### ISSUE TITLE
Feature request: equivalent annotation of `+kubebuilder:validation:UniqueItems` for uniqueness of field among list of structs

### ISSUE THREAD

**Issue by mattwelke** [kubernetes-sigs/controller-tools#868]
I'm submitting a feature request for a feature that would help with a use case my team and I have.

# Summary

An annotation that could be used to perform the following CRD validation:

* CRs being invalid means that among a list of structs in the spec, for a particular field, there are duplicate values
* Without having to create a validating webhook
* With linear time complexity instead of quadratic

# Background

We have a CRD that looks like this:

```go
type OurSpec struct {
	Foos []string `json:"foos,omitempty"`
}

type Foo struct {
	ID  string `json:"id"`
	Bar string `json:"bar"`
}
```

It's important that among all `Foo` structs in the spec, there are no duplicate `ID` field values.

If `Foos` were of type `[]string` (or some other type than a struct type), I could use the `+kubebuilder:validation:UniqueItems` on such a field. That annotation can be used for lists of struct types too, but it's also important for this use case that the logic for determining duplicates be based only on the `ID` field of `Foo`, not `Foo` completely.

The workaround we've used so far is to use a [validation rule with CEL](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation-rules).

We use an expression like this, which determines whether there are any duplicates by performing an iteration through the entire set, for every item in the set. This allows us to do this kind of validation even though we're working with structs and we're interested in a particular field:

```
self.all(e, size(self.filter(x, x.id == e.id)) == 1)
```

In the spec, we use the expression like this:

```go
//+kubebuilder:validation:XValidation:message="All foos must have unique IDs",rule="<cel>)"
```

The problem with this approach is the time complexity of the algorithm. It's greater than linear, and this makes it expensive.

When using this validation rule alone, we get errors when applying the CRDs warning us that the validation is too expensive:

```
* spec.validation.openAPIV3Schema.properties[spec].properties[foos].x-kubernetes-validations[0].rule: Forbidden: estimated rule cost exceeds budget by factor of more than 100x (try simplifying the rule, or adding maxItems, maxProperties, and maxLength where arrays, maps, and strings are declared)
```

We find that for this CEL expression, we can only get the expensiveness down to an acceptable level by severely limiting the size of the list via `MaxItems`. For example, I had to bring this limit down to 5 for it to work when applying the CRDs:

```go
type OurSpec struct {
	//+kubebuilder:validation:MaxItems=5
	//+kubebuilder:validation:XValidation:message="Among foos, IDs must be unique",rule="self.all(e, size(self.filter(x, x.id == e.id)) == 1)"
	Foos []Foo `json:"foos,omitempty"`
}
```

This presents problems when trying to use this for real world use cases. In cases where 5 isn't great enough, or it is, but you want to add more `[]<type>` fields that have similar requirements, it becomes too limited.

I know that I could use Go code to write an algorithm that would check for uniqueness efficiently. For example, I could make a `map[string]bool` and iterate through the list just once. But, this would mean using a validating webhook, which I'd like to avoid. I'd like to be able to use these annotations that allow validation without a webhook if possible.

**Comment by mattwelke** [comment]
Closing in favor of https://github.com/kubernetes-sigs/kubebuilder/issues/3710. Intention is to start from most user-facing repo and replace with issues in repos for tools kubebuilder uses if applicable.

**Comment by camilamacedo86** [comment]
The RFE requested here would be implemented in this project.
Kubebuilder just consume this project
Therefore, the right place to have this discussion is here, where its maintainers will be able to verify if it is or not acceptable. If accepted, kubebuilder will provide the functionality when it is released in controller-gen.

Be aware that indeed the documentation available in Kubebuilder is generated automatically from the comments and data added to this project via the source code. 

Adding here the history of comments made in Kubebuilder:

**Comment by camilamacedo86** [comment]
From @JoelSpeed 

> The problem with this approach is the time complexity of the algorithm. It's greater than linear, and this makes it expensive.

The operation of supporting the `UniqueItems` is equally expensive, it's just that it's hidden from the user in this case.

> The workaround we've used so far is to use a [validation rule with CEL](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#validation-rules).

This is actually probably the correct path forward rather then directly supporting this in kubebuilder. Supporting it in kubebuilder would allow users to blindly add very complex validations without any thought for the complexity of the rules in question.

> When using this validation rule alone, we get errors when applying the CRDs warning us that the validation is too expensive:

* spec.validation.openAPIV3Schema.properties[spec].properties[foos].x-kubernetes-validations[0].rule: Forbidden: estimated rule cost exceeds budget by factor of more than 100x (try simplifying the rule, or adding maxItems, maxProperties, and maxLength where arrays, maps, and strings are declared)

We find that for this CEL expression, we can only get the expensiveness down to an acceptable level by severely limiting the size of the list via MaxItems.

This is the expectation, where you have complex validations you must limit the length of your inputs, this is, in general good practice anyway.

Bear in mind that the cost calculation not only takes into account the length of the list, but also what the size of the elements within them are. So, if you have an unbounded length string within your struct, that will not be helping you here. Make sure to add maximum sizes to all structs!

---

Given everything I have said above, I don't think CEL or UniqueItems is what you want for your particular use case.

If I have understood correctly, your desire is to have a list of items, where there is one field in the list that is unique. This is a standard thing in kube, for example, the list of containers in a pod must all have unique names.

The following validation will achieve what you want, set the list to a map type and add the `id` field as the map key
```
// +listType=map
// +listMapKey=id
```
The validations will ensure every list has a unique `id` entry. This also sets you up for server side apply where different actors will be able to update their own entries in the list without affecting the whole list.

**Comment by camilamacedo86** [comment]
From @mattwelke 

@JoelSpeed Thanks for the suggestions.

> Bear in mind that the cost calculation not only takes into account the length of the list, but also what the size of the elements within them are. So, if you have an unbounded length string within your struct, that will not be helping you here. Make sure to add maximum sizes to all structs!

This is a great suggestion. We completely forgot about this and I think it'll make a big improvement. It should allow us to squeeze in a lot more items via `MaxItems`.

> `// +listType=map` and `// +listMapKey=id`

We actually prefer using structs over maps because it means things are more strongly typed and we can add documentation for each field.

But, we found https://github.com/kubernetes-sigs/controller-tools/issues/435#issuecomment-1155413943 which talks about how you can use those markers on structs too.

```go
type BarSpec struct {
	// +listType=map
	// +listMapKey=id
	Foos []Foo `json:"foos,omitempty"`
}

type Foo struct {
	ID    string `json:"id"`
	Other string `json:"other"`
}
```

I tested this and it worked too!

But unfortunately, it was determined by k8s to be just as expensive as the CEL approach. I actually find this surprising because as far as I know, one could determine uniqueness in an inexpensive way by doing something like this:

```go
package main

import "fmt"

func duplicate(items []string) *string {
	seen := map[string]bool{}

	for _, str := range items {
		if _, ok := seen[str]; ok {
			// Duplicate found!
			return &str
		}
		seen[str] = true
	}

	// No duplicates found.
	return nil
}

func main() {
	if dupStr := duplicate([]string{"a", "b", "b", "c"}); dupStr != nil {
		fmt.Printf("Duplicate found: %s\n", *dupStr)
	} else {
		fmt.Printf("No duplicates found.\n")
	}
}
```

```
Duplicate found: b
```

**Comment by camilamacedo86** [comment]
From @JoelSpeed 

> We actually prefer using structs over maps because it means things are more strongly typed and we can add documentation for each field.

Maps are discouraged (forbidden even) in Kube API types. The markers I'm suggesting do not mean you have to use maps. They are designed for lists, hence, `listType`.

> I tested this and it worked too!

Yep, what you have in that example looks like what I was expecting.

> But unfortunately, it was deemed by k8s to be just as expensive as the CEL approach.

Can you provide the error message that came out? To my knowledge the `listType` and `listMapKey` do not have cost counting, only CEL validations have cost counting so I don't think your error will have been from this

**Comment by camilamacedo86** [comment]
@mattwelke 

Could you please re-open this one?
I have no longer permission in this repo, indeed to re-open your issue.

**Comment by JoelSpeed** [comment]
> Sorry. To clarify, what I meant was that we needed to use a list regardless, and it was just a matter of what type to use with the list. So []OurStruct vs. []map[K]V. We prefer []OurStruct for the reasons I mentioned.

We are agreeing with each other. My point was that `[]map[K]V` is forbidden in kube, and that if you want a "map", you should use `[]K` and then use the `listType` and `listMapKey` markers to make it behave almost like a map

**Comment by JoelSpeed** [comment]
I actually don't think this should be re-opened. Uniqueness is very hard and can be achieved through CEL validation now anyway. CEL has the added advantage of cost estimates, making CRD authors think about the complexity of the operations they are trying to get the apiserver to do.

If we implement this, we allow users to circumvent the cost calculation and that in turn could lead to overly complex calculations being performed on every CRD write, causing instability in the API server.

**Comment by camilamacedo86** [comment]
Thank you @JoelSpeed 

So, unfortunately, this one cannot be accepted currently.
