### ISSUE TITLE
Document supported version(s) of Go

### ISSUE THREAD

**Issue by mattwelke** [kubernetes-sigs/controller-tools#886]
A GitHub user notes in https://github.com/kubernetes-sigs/controller-tools/issues/880#issuecomment-1938508012 that the presence of `1.21` in https://github.com/kubernetes-sigs/controller-tools/blob/master/go.mod#L3, according to Go conventions, doesn't mean that the project doesn't support any other version of Go than 1.21. It simply means that the Go code contained within it requires [at least Go 1.21](https://go.dev/ref/mod#go-mod-file-go) to compile.

Of course at the same time, it makes sense that a project may only support *up to* a certain Go version, because of bugs present in the new version, breaking changes, or simply because the maintainers want to take a more careful approach where they vet new versions of Go first with the code. So stating "only Go 1.21 is supported right now" is perfectly valid.

I propose that information be documented in the README that conveys which Go version(s) are supported ([is it just 1.21?](https://github.com/kubernetes-sigs/controller-tools/issues/880#issuecomment-1937632135)).

**Comment by sbueringer** [comment]
Makes sense to me!

**Comment by sbueringer** [comment]
Seems like atm we're running tests with Go 1.20? (https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/controller-tools/controller-tools-presubmits-master.yaml https://github.com/kubernetes-sigs/controller-tools/blob/master/test.sh)
