### ISSUE TITLE
Strict validation for unrecognized `+kubebuilder` markers in controller-gen

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/controller-tools#887]
I am recently hurt by a lowercase-uppercase mistake in `+kubebuilder:validation:enum` vs `+kubebuilder:validation:Enum` marker (which is not even a misspelling).

So I'm proposing that `controller-gen` should try to do something with every single `+kubebuilder:*` marker and **fail** if it does not recognize the marker.

**Comment by sbueringer** [comment]
Sounds good to me

**Comment by ahmetb** [comment]
I took a quick look, this doesn't seem easily possible as `controller-gen` has a wide variety of markers that don't start with `+kubebuilder:` (e.g. `+output`, `+groupName`, `+optional`).

So there's no way to check a `+marker` against a known list of registered markers, and fail if an unknown one (or one that has a typo) is seen. It would likely require a lot of change.

/close
