### ISSUE TITLE
kubebuilder default not work for required field

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/controller-tools#893]
This is how I defined the field:
```
	// Type defines the rollout strategy, it can only be “RollingUpdate” for now.
	//
	// +kubebuilder:validation:Enum={RollingUpdate}
	// +kubebuilder:default=RollingUpdate
	Type RolloutStrategyType `json:"type"`
```
What I expected is the `RolloutStrategyType` has a default `RollingUpdate` value when unset, however, when I apply the build yaml, error emits:
`spec.rolloutStrategy.type: Unsupported value: "": supported values: "RollingUpdate"`

/kind bug
/kind support

seek for help.

**Comment by kerthcet** [comment]
If I set this a pointer type, it works. Is this as expected?

**Comment by JoelSpeed** [comment]
This is expected behaviour. In Kube, the required field checks are applied on admission of the request, however, defaults are applied on read if the value is not otherwise set. To use a kubebuilder default, you must make the field optional and ensure that the field is omitted from the json serialisation (`omitempty` and pointer type where appropriate)

**Comment by kerthcet** [comment]
Thanks for the detailed explanation @JoelSpeed solved parts of my confusions, however, set an optional field with a non-pointer type seems violating the API convention https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#optional-vs-required. Although a bit of kubernetes APIs does this way. 😅

**Comment by JoelSpeed** [comment]
My comment there specifically is for types that are nullable (that the json serialiser can detect are empty), that they don't need to be pointers, this is basically, for Kube APIs at least, slice types. It's not common to see `*[]<t>` in kube APIs as far as I'm aware, even when optional.
