### ISSUE TITLE
Unnecessary `---` in beginning of YAMLs created by `controller-gen`

### ISSUE THREAD

**Issue by mateusoliveira43** [kubernetes-sigs/controller-tools#909]
Using this test project https://github.com/kubernetes-sigs/kubebuilder/tree/master/testdata/project-v4 as an example, if you run `make run`, which under the rug runs
```sh
controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
```
4 YAML files will be created: 3 CRDs https://github.com/kubernetes-sigs/kubebuilder/tree/master/testdata/project-v4/config/crd/bases and 1 ClusterRole https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v4/config/rbac/role.yaml

All this files have a `---` at the beginning of their files, which is unnecessary.

Can it be removed? thanks!

**Comment by sbueringer** [comment]
Not sure if it's unnecessary. I wonder if some folks are just concatenating the files we generate and then this line would be missing.

So this could break a lot of folks

**Comment by sbueringer** [comment]
Let's see if anyone else has context on it
