### ISSUE TITLE
Should respect +required

### ISSUE THREAD

**Issue by thockin** [kubernetes-sigs/controller-tools#943]
### What do you want to happen?

Generating CRD from a field defined as:

```
// +required
Foo string `json:"foo,omitempty" protobuf:"bytes,1,opt,name=foo"`
```

...should be determined as "required" and not optional.  It's a little wonky, but context is https://github.com/kubernetes/kubernetes/pull/124553#discussion_r1586396834 and https://github.com/kubernetes/kubernetes/pull/124553#discussion_r1588479452

**Comment by liggitt** [comment]
`omitempty` means a zero value should not be serialized. That is independent of whether a value is required. An explicit `+required` indicates this in kube-openapi / kubernetes API types

**Comment by sbueringer** [comment]
Agree, we should support+required. Just like we already support +optional
