### ISSUE TITLE
kubebuilder:validation:Format should apply to array items, not to array

### ISSUE THREAD

**Issue by justinsb** [kubernetes-sigs/controller-tools#953]
This is likely a regression / reoccurence of an issue that was originally raised in #141 and fixed in #143, but was broken by refactoring accompanied by removal of the test cases (which would have prevented regression).  As such I don't believe the regression is deliberate, although I'm not 100% certain of the correct behaviour.

I have tried to add test cases to show the issue in #952 (based on the original test cases).  I believe the format directive should apply to the item, not the slice.  To cite the problem from #952 so that we can first agree that the current behaviour is wrong:

```
	// +kubebuilder:validation:Format=ipv4
	Addresses []string `json:"addresses"`
```

Currently this produces:

```
+              addresses:
+                format: ipv4
+                items:
+                  type: string
+                type: array
```

I believe it should produce:
```
+              addresses:
+                items:
+                  format: ipv4
+                  type: string
+                type: array
```

**Comment by sbueringer** [comment]
I think the current behavior is correct. See also: https://github.com/kubernetes-sigs/controller-tools/issues/342

Since https://github.com/kubernetes-sigs/controller-tools/pull/898 it's now possible to define markers directly on the slice items via e.g. `// +kubebuilder:validation:items:MinLength=1`

**Comment by sbueringer** [comment]
/close

See above. Feel free to reopen if necessary
